export const ProvinceEnum = {
  Bali: 'Bali',
  BangkaBelitung: 'BangkaBelitung',
  Banten: 'Banten',
  Bengkulu: 'Bengkulu',
  DIYogyakarta: 'DIYogyakarta',
  DKIJakarta: 'DKIJakarta',
  Gorontalo: 'Gorontalo',
  Jambi: 'Jambi',
  JawaBarat: 'JawaBarat',
  JawaTengah: 'JawaTengah',
  JawaTimur: 'JawaTimur',
  KalimantanBarat: 'KalimantanBarat',
  KalimantanSelatan: 'KalimantanSelatan',
  KalimantanTengah: 'KalimantanTengah',
  KalimantanTimur: 'KalimantanTimur',
  KalimantanUtara: 'KalimantanUtara',
  KepulauanRiau: 'KepulauanRiau',
  Lampung: 'Lampung',
  Maluku: 'Maluku',
  MalukuUtara: 'MalukuUtara',
  NanggroeAcehDarussalam: 'NanggroeAcehDarussalam',
  NusaTenggaraBarat: 'NusaTenggaraBarat',
  NusaTenggaraTimur: 'NusaTenggaraTimur',
  Papua: 'Papua',
  PapuaBarat: 'PapuaBarat',
  Riau: 'Riau',
  SulawesiBarat: 'SulawesiBarat',
  SulawesiSelatan: 'SulawesiSelatan',
  SulawesiTengah: 'SulawesiTengah',
  SulawesiTenggara: 'SulawesiTenggara',
  SulawesiUtara: 'SulawesiUtara',
  SumateraBarat: 'SumateraBarat',
  SumateraSelatan: 'SumateraSelatan',
  SumateraUtara: 'SumateraUtara',
}

export const provinceObject = {
  Bali: 'Bali',
  BangkaBelitung: 'Bangka Belitung',
  Banten: 'Banten',
  Bengkulu: 'Bengkulu',
  DIYogyakarta: 'DI Yogyakarta',
  DKIJakarta: 'DKI Jakarta',
  Gorontalo: 'Gorontalo',
  Jambi: 'Jambi',
  JawaBarat: 'Jawa Barat',
  JawaTengah: 'Jawa Tengah',
  JawaTimur: 'Jawa Timur',
  KalimantanBarat: 'Kalimantan Barat',
  KalimantanSelatan: 'Kalimantan Selatan',
  KalimantanTengah: 'Kalimantan Tengah',
  KalimantanTimur: 'Kalimantan Timur',
  KalimantanUtara: 'Kalimantan Utara',
  KepulauanRiau: 'Kepulauan Riau',
  Lampung: 'Lampung',
  Maluku: 'Maluku',
  MalukuUtara: 'Maluku Utara',
  NanggroeAcehDarussalam: 'Nanggroe Aceh Darussalam',
  NusaTenggaraBarat: 'Nusa Tenggara Barat',
  NusaTenggaraTimur: 'Nusa Tenggara Timur',
  Papua: 'Papua',
  PapuaBarat: 'Papua Barat',
  Riau: 'Riau',
  SulawesiBarat: 'Sulawesi Barat',
  SulawesiSelatan: 'Sulawesi Selatan',
  SulawesiTengah: 'Sulawesi Tengah',
  SulawesiTenggara: 'Sulawesi Tenggara',
  SulawesiUtara: 'Sulawesi Utara',
  SumateraBarat: 'Sumatera Barat',
  SumateraSelatan: 'Sumatera Selatan',
  SumateraUtara: 'Sumatera Utara',
}
