export const cityEnumObject = {
  AcehBarat: 'AcehBarat',
  AcehBaratDaya: 'AcehBaratDaya',
  AcehBesar: 'AcehBesar',
  AcehJaya: 'AcehJaya',
  AcehSelatan: 'AcehSelatan',
  AcehSingkil: 'AcehSingkil',
  AcehTamiang: 'AcehTamiang',
  AcehTengah: 'AcehTengah',
  AcehTenggara: 'AcehTenggara',
  AcehTimur: 'AcehTimur',
  AcehUtara: 'AcehUtara',
  Agam: 'Agam',
  Alor: 'Alor',
  Ambon: 'Ambon',
  Asahan: 'Asahan',
  Asmat: 'Asmat',
  Badung: 'Badung',
  Balangan: 'Balangan',
  Balikpapan: 'Balikpapan',
  BandaAceh: 'BandaAceh',
  BandarLampung: 'BandarLampung',
  Bandung: 'Bandung',
  BandungBarat: 'BandungBarat',
  Banggai: 'Banggai',
  BanggaiKepulauan: 'BanggaiKepulauan',
  Bangka: 'Bangka',
  BangkaBarat: 'BangkaBarat',
  BangkaSelatan: 'BangkaSelatan',
  BangkaTengah: 'BangkaTengah',
  Bangkalan: 'Bangkalan',
  Bangli: 'Bangli',
  Banjar: 'Banjar',
  Banjarbaru: 'Banjarbaru',
  Banjarmasin: 'Banjarmasin',
  Banjarnegara: 'Banjarnegara',
  Bantaeng: 'Bantaeng',
  Bantul: 'Bantul',
  Banyuasin: 'Banyuasin',
  Banyumas: 'Banyumas',
  Banyuwangi: 'Banyuwangi',
  BaritoKuala: 'BaritoKuala',
  BaritoSelatan: 'BaritoSelatan',
  BaritoTimur: 'BaritoTimur',
  BaritoUtara: 'BaritoUtara',
  Barru: 'Barru',
  Batam: 'Batam',
  Batang: 'Batang',
  BatangHari: 'BatangHari',
  Batu: 'Batu',
  BatuBara: 'BatuBara',
  Bau: 'Bau',
  Bekasi: 'Bekasi',
  Belitung: 'Belitung',
  BelitungTimur: 'BelitungTimur',
  Belu: 'Belu',
  BenerMeriah: 'BenerMeriah',
  Bengkalis: 'Bengkalis',
  Bengkayang: 'Bengkayang',
  Bengkulu: 'Bengkulu',
  BengkuluSelatan: 'BengkuluSelatan',
  BengkuluTengah: 'BengkuluTengah',
  BengkuluUtara: 'BengkuluUtara',
  Berau: 'Berau',
  BiakNumfor: 'BiakNumfor',
  Bima: 'Bima',
  Binjai: 'Binjai',
  Bintan: 'Bintan',
  Bireuen: 'Bireuen',
  Bitung: 'Bitung',
  Blitar: 'Blitar',
  Blora: 'Blora',
  Boalemo: 'Boalemo',
  Bogor: 'Bogor',
  Bojonegoro: 'Bojonegoro',
  'BolaangMongondow(Bolmong)': 'BolaangMongondow(Bolmong)',
  BolaangMongondowSelatan: 'BolaangMongondowSelatan',
  BolaangMongondowTimur: 'BolaangMongondowTimur',
  BolaangMongondowUtara: 'BolaangMongondowUtara',
  Bombana: 'Bombana',
  Bondowoso: 'Bondowoso',
  Bone: 'Bone',
  BoneBolango: 'BoneBolango',
  Bontang: 'Bontang',
  BovenDigoel: 'BovenDigoel',
  Boyolali: 'Boyolali',
  Brebes: 'Brebes',
  Bukittinggi: 'Bukittinggi',
  Buleleng: 'Buleleng',
  Bulukumba: 'Bulukumba',
  'Bulungan(Bulongan)': 'Bulungan(Bulongan)',
  Bungo: 'Bungo',
  Buol: 'Buol',
  Buru: 'Buru',
  BuruSelatan: 'BuruSelatan',
  Buton: 'Buton',
  ButonUtara: 'ButonUtara',
  Ciamis: 'Ciamis',
  Cianjur: 'Cianjur',
  Cilacap: 'Cilacap',
  Cilegon: 'Cilegon',
  Cimahi: 'Cimahi',
  Cirebon: 'Cirebon',
  Dairi: 'Dairi',
  'Deiyai(Deliyai)': 'Deiyai(Deliyai)',
  DeliSerdang: 'DeliSerdang',
  Demak: 'Demak',
  Denpasar: 'Denpasar',
  Depok: 'Depok',
  Dharmasraya: 'Dharmasraya',
  Dogiyai: 'Dogiyai',
  Dompu: 'Dompu',
  Donggala: 'Donggala',
  Dumai: 'Dumai',
  EmpatLawang: 'EmpatLawang',
  Ende: 'Ende',
  Enrekang: 'Enrekang',
  Fakfak: 'Fakfak',
  FloresTimur: 'FloresTimur',
  Garut: 'Garut',
  GayoLues: 'GayoLues',
  Gianyar: 'Gianyar',
  Gorontalo: 'Gorontalo',
  GorontaloUtara: 'GorontaloUtara',
  Gowa: 'Gowa',
  Gresik: 'Gresik',
  Grobogan: 'Grobogan',
  GunungKidul: 'GunungKidul',
  GunungMas: 'GunungMas',
  Gunungsitoli: 'Gunungsitoli',
  HalmaheraBarat: 'HalmaheraBarat',
  HalmaheraSelatan: 'HalmaheraSelatan',
  HalmaheraTengah: 'HalmaheraTengah',
  HalmaheraTimur: 'HalmaheraTimur',
  HalmaheraUtara: 'HalmaheraUtara',
  HuluSungaiSelatan: 'HuluSungaiSelatan',
  HuluSungaiTengah: 'HuluSungaiTengah',
  HuluSungaiUtara: 'HuluSungaiUtara',
  HumbangHasundutan: 'HumbangHasundutan',
  IndragiriHilir: 'IndragiriHilir',
  IndragiriHulu: 'IndragiriHulu',
  Indramayu: 'Indramayu',
  IntanJaya: 'IntanJaya',
  JakartaBarat: 'JakartaBarat',
  JakartaPusat: 'JakartaPusat',
  JakartaSelatan: 'JakartaSelatan',
  JakartaTimur: 'JakartaTimur',
  JakartaUtara: 'JakartaUtara',
  Jambi: 'Jambi',
  Jayapura: 'Jayapura',
  Jayawijaya: 'Jayawijaya',
  Jember: 'Jember',
  Jembrana: 'Jembrana',
  Jeneponto: 'Jeneponto',
  Jepara: 'Jepara',
  Jombang: 'Jombang',
  Kaimana: 'Kaimana',
  Kampar: 'Kampar',
  Kapuas: 'Kapuas',
  KapuasHulu: 'KapuasHulu',
  Karanganyar: 'Karanganyar',
  Karangasem: 'Karangasem',
  Karawang: 'Karawang',
  Karimun: 'Karimun',
  Karo: 'Karo',
  Katingan: 'Katingan',
  Kaur: 'Kaur',
  KayongUtara: 'KayongUtara',
  Kebumen: 'Kebumen',
  Kediri: 'Kediri',
  Keerom: 'Keerom',
  Kendal: 'Kendal',
  Kendari: 'Kendari',
  Kepahiang: 'Kepahiang',
  KepulauanAnambas: 'KepulauanAnambas',
  KepulauanAru: 'KepulauanAru',
  KepulauanMentawai: 'KepulauanMentawai',
  KepulauanMeranti: 'KepulauanMeranti',
  KepulauanSangihe: 'KepulauanSangihe',
  KepulauanSeribu: 'KepulauanSeribu',
  'KepulauanSiauTagulandangBiaro(Sitaro)':
    'KepulauanSiauTagulandangBiaro(Sitaro)',
  KepulauanSula: 'KepulauanSula',
  KepulauanTalaud: 'KepulauanTalaud',
  'KepulauanYapen(YapenWaropen)': 'KepulauanYapen(YapenWaropen)',
  Kerinci: 'Kerinci',
  Ketapang: 'Ketapang',
  Klaten: 'Klaten',
  Klungkung: 'Klungkung',
  Kolaka: 'Kolaka',
  KolakaUtara: 'KolakaUtara',
  Konawe: 'Konawe',
  KonaweSelatan: 'KonaweSelatan',
  KonaweUtara: 'KonaweUtara',
  Kotabaru: 'Kotabaru',
  Kotamobagu: 'Kotamobagu',
  KotawaringinBarat: 'KotawaringinBarat',
  KotawaringinTimur: 'KotawaringinTimur',
  KuantanSingingi: 'KuantanSingingi',
  KubuRaya: 'KubuRaya',
  Kudus: 'Kudus',
  KulonProgo: 'KulonProgo',
  Kuningan: 'Kuningan',
  Kupang: 'Kupang',
  KutaiBarat: 'KutaiBarat',
  KutaiKartanegara: 'KutaiKartanegara',
  KutaiTimur: 'KutaiTimur',
  LabuhanBatu: 'LabuhanBatu',
  LabuhanBatuSelatan: 'LabuhanBatuSelatan',
  LabuhanBatuUtara: 'LabuhanBatuUtara',
  Lahat: 'Lahat',
  Lamandau: 'Lamandau',
  Lamongan: 'Lamongan',
  LampungBarat: 'LampungBarat',
  LampungSelatan: 'LampungSelatan',
  LampungTengah: 'LampungTengah',
  LampungTimur: 'LampungTimur',
  LampungUtara: 'LampungUtara',
  Landak: 'Landak',
  Langkat: 'Langkat',
  Langsa: 'Langsa',
  LannyJaya: 'LannyJaya',
  Lebak: 'Lebak',
  Lebong: 'Lebong',
  Lembata: 'Lembata',
  Lhokseumawe: 'Lhokseumawe',
  LimaPuluhKoto: 'LimaPuluhKoto',
  Lingga: 'Lingga',
  LombokBarat: 'LombokBarat',
  LombokTengah: 'LombokTengah',
  LombokTimur: 'LombokTimur',
  LombokUtara: 'LombokUtara',
  LubukLinggau: 'LubukLinggau',
  Lumajang: 'Lumajang',
  Luwu: 'Luwu',
  LuwuTimur: 'LuwuTimur',
  LuwuUtara: 'LuwuUtara',
  Madiun: 'Madiun',
  Magelang: 'Magelang',
  Magetan: 'Magetan',
  Majalengka: 'Majalengka',
  Majene: 'Majene',
  Makassar: 'Makassar',
  Malang: 'Malang',
  Malinau: 'Malinau',
  MalukuBaratDaya: 'MalukuBaratDaya',
  MalukuTengah: 'MalukuTengah',
  MalukuTenggara: 'MalukuTenggara',
  MalukuTenggaraBarat: 'MalukuTenggaraBarat',
  Mamasa: 'Mamasa',
  MamberamoRaya: 'MamberamoRaya',
  MamberamoTengah: 'MamberamoTengah',
  Mamuju: 'Mamuju',
  MamujuUtara: 'MamujuUtara',
  Manado: 'Manado',
  MandailingNatal: 'MandailingNatal',
  Manggarai: 'Manggarai',
  ManggaraiBarat: 'ManggaraiBarat',
  ManggaraiTimur: 'ManggaraiTimur',
  Manokwari: 'Manokwari',
  ManokwariSelatan: 'ManokwariSelatan',
  Mappi: 'Mappi',
  Maros: 'Maros',
  Mataram: 'Mataram',
  Maybrat: 'Maybrat',
  Medan: 'Medan',
  Melawi: 'Melawi',
  Merangin: 'Merangin',
  Merauke: 'Merauke',
  Mesuji: 'Mesuji',
  Metro: 'Metro',
  Mimika: 'Mimika',
  Minahasa: 'Minahasa',
  MinahasaSelatan: 'MinahasaSelatan',
  MinahasaTenggara: 'MinahasaTenggara',
  MinahasaUtara: 'MinahasaUtara',
  Mojokerto: 'Mojokerto',
  Morowali: 'Morowali',
  MuaraEnim: 'MuaraEnim',
  MuaroJambi: 'MuaroJambi',
  MukoMuko: 'MukoMuko',
  Muna: 'Muna',
  MurungRaya: 'MurungRaya',
  MusiBanyuasin: 'MusiBanyuasin',
  MusiRawas: 'MusiRawas',
  Nabire: 'Nabire',
  NaganRaya: 'NaganRaya',
  Nagekeo: 'Nagekeo',
  Natuna: 'Natuna',
  Nduga: 'Nduga',
  Ngada: 'Ngada',
  Nganjuk: 'Nganjuk',
  Ngawi: 'Ngawi',
  Nias: 'Nias',
  NiasBarat: 'NiasBarat',
  NiasSelatan: 'NiasSelatan',
  NiasUtara: 'NiasUtara',
  Nunukan: 'Nunukan',
  OganIlir: 'OganIlir',
  OganKomeringIlir: 'OganKomeringIlir',
  OganKomeringUlu: 'OganKomeringUlu',
  OganKomeringUluSelatan: 'OganKomeringUluSelatan',
  OganKomeringUluTimur: 'OganKomeringUluTimur',
  Pacitan: 'Pacitan',
  Padang: 'Padang',
  PadangLawas: 'PadangLawas',
  PadangLawasUtara: 'PadangLawasUtara',
  PadangPanjang: 'PadangPanjang',
  PadangPariaman: 'PadangPariaman',
  PadangSidempuan: 'PadangSidempuan',
  PagarAlam: 'PagarAlam',
  PakpakBharat: 'PakpakBharat',
  PalangkaRaya: 'PalangkaRaya',
  Palembang: 'Palembang',
  Palopo: 'Palopo',
  Palu: 'Palu',
  Pamekasan: 'Pamekasan',
  Pandeglang: 'Pandeglang',
  Pangandaran: 'Pangandaran',
  PangkajeneKepulauan: 'PangkajeneKepulauan',
  PangkalPinang: 'PangkalPinang',
  Paniai: 'Paniai',
  Parepare: 'Parepare',
  Pariaman: 'Pariaman',
  ParigiMoutong: 'ParigiMoutong',
  Pasaman: 'Pasaman',
  PasamanBarat: 'PasamanBarat',
  Paser: 'Paser',
  Pasuruan: 'Pasuruan',
  Pati: 'Pati',
  Payakumbuh: 'Payakumbuh',
  PegununganArfak: 'PegununganArfak',
  PegununganBintang: 'PegununganBintang',
  Pekalongan: 'Pekalongan',
  Pekanbaru: 'Pekanbaru',
  Pelalawan: 'Pelalawan',
  Pemalang: 'Pemalang',
  PematangSiantar: 'PematangSiantar',
  PenajamPaserUtara: 'PenajamPaserUtara',
  Pesawaran: 'Pesawaran',
  PesisirBarat: 'PesisirBarat',
  PesisirSelatan: 'PesisirSelatan',
  Pidie: 'Pidie',
  PidieJaya: 'PidieJaya',
  Pinrang: 'Pinrang',
  Pohuwato: 'Pohuwato',
  PolewaliMandar: 'PolewaliMandar',
  Ponorogo: 'Ponorogo',
  Pontianak: 'Pontianak',
  Poso: 'Poso',
  Prabumulih: 'Prabumulih',
  Pringsewu: 'Pringsewu',
  Probolinggo: 'Probolinggo',
  PulangPisau: 'PulangPisau',
  PulauMorotai: 'PulauMorotai',
  Puncak: 'Puncak',
  PuncakJaya: 'PuncakJaya',
  Purbalingga: 'Purbalingga',
  Purwakarta: 'Purwakarta',
  Purworejo: 'Purworejo',
  RajaAmpat: 'RajaAmpat',
  RejangLebong: 'RejangLebong',
  Rembang: 'Rembang',
  RokanHilir: 'RokanHilir',
  RokanHulu: 'RokanHulu',
  RoteNdao: 'RoteNdao',
  Sabang: 'Sabang',
  SabuRaijua: 'SabuRaijua',
  Salatiga: 'Salatiga',
  Samarinda: 'Samarinda',
  Sambas: 'Sambas',
  Samosir: 'Samosir',
  Sampang: 'Sampang',
  Sanggau: 'Sanggau',
  Sarmi: 'Sarmi',
  Sarolangun: 'Sarolangun',
  SawahLunto: 'SawahLunto',
  Sekadau: 'Sekadau',
  'Selayar(KepulauanSelayar)': 'Selayar(KepulauanSelayar)',
  Seluma: 'Seluma',
  Semarang: 'Semarang',
  SeramBagianBarat: 'SeramBagianBarat',
  SeramBagianTimur: 'SeramBagianTimur',
  Serang: 'Serang',
  SerdangBedagai: 'SerdangBedagai',
  Seruyan: 'Seruyan',
  Siak: 'Siak',
  Sibolga: 'Sibolga',
  SidenrengRappang: 'SidenrengRappang',
  Sidoarjo: 'Sidoarjo',
  Sigi: 'Sigi',
  'Sijunjung(SawahLuntoSijunjung)': 'Sijunjung(SawahLuntoSijunjung)',
  Sikka: 'Sikka',
  Simalungun: 'Simalungun',
  Simeulue: 'Simeulue',
  Singkawang: 'Singkawang',
  Sinjai: 'Sinjai',
  Sintang: 'Sintang',
  Situbondo: 'Situbondo',
  Sleman: 'Sleman',
  Solok: 'Solok',
  SolokSelatan: 'SolokSelatan',
  Soppeng: 'Soppeng',
  Sorong: 'Sorong',
  SorongSelatan: 'SorongSelatan',
  Sragen: 'Sragen',
  Subang: 'Subang',
  Subulussalam: 'Subulussalam',
  Sukabumi: 'Sukabumi',
  Sukamara: 'Sukamara',
  Sukoharjo: 'Sukoharjo',
  SumbaBarat: 'SumbaBarat',
  SumbaBaratDaya: 'SumbaBaratDaya',
  SumbaTengah: 'SumbaTengah',
  SumbaTimur: 'SumbaTimur',
  Sumbawa: 'Sumbawa',
  SumbawaBarat: 'SumbawaBarat',
  Sumedang: 'Sumedang',
  Sumenep: 'Sumenep',
  Sungaipenuh: 'Sungaipenuh',
  Supiori: 'Supiori',
  Surabaya: 'Surabaya',
  'Surakarta(Solo)': 'Surakarta(Solo)',
  Tabalong: 'Tabalong',
  Tabanan: 'Tabanan',
  Takalar: 'Takalar',
  Tambrauw: 'Tambrauw',
  TanaTidung: 'TanaTidung',
  TanaToraja: 'TanaToraja',
  TanahBumbu: 'TanahBumbu',
  TanahDatar: 'TanahDatar',
  TanahLaut: 'TanahLaut',
  Tangerang: 'Tangerang',
  TangerangSelatan: 'TangerangSelatan',
  Tanggamus: 'Tanggamus',
  TanjungBalai: 'TanjungBalai',
  TanjungJabungBarat: 'TanjungJabungBarat',
  TanjungJabungTimur: 'TanjungJabungTimur',
  TanjungPinang: 'TanjungPinang',
  TapanuliSelatan: 'TapanuliSelatan',
  TapanuliTengah: 'TapanuliTengah',
  TapanuliUtara: 'TapanuliUtara',
  Tapin: 'Tapin',
  Tarakan: 'Tarakan',
  Tasikmalaya: 'Tasikmalaya',
  TebingTinggi: 'TebingTinggi',
  Tebo: 'Tebo',
  Tegal: 'Tegal',
  TelukBintuni: 'TelukBintuni',
  TelukWondama: 'TelukWondama',
  Temanggung: 'Temanggung',
  Ternate: 'Ternate',
  TidoreKepulauan: 'TidoreKepulauan',
  TimorTengahSelatan: 'TimorTengahSelatan',
  TimorTengahUtara: 'TimorTengahUtara',
  TobaSamosir: 'TobaSamosir',
  TojoUna: 'TojoUna',
  Toli: 'Toli',
  Tolikara: 'Tolikara',
  Tomohon: 'Tomohon',
  TorajaUtara: 'TorajaUtara',
  Trenggalek: 'Trenggalek',
  Tual: 'Tual',
  Tuban: 'Tuban',
  TulangBawang: 'TulangBawang',
  TulangBawangBarat: 'TulangBawangBarat',
  Tulungagung: 'Tulungagung',
  Wajo: 'Wajo',
  Wakatobi: 'Wakatobi',
  Waropen: 'Waropen',
  WayKanan: 'WayKanan',
  Wonogiri: 'Wonogiri',
  Wonosobo: 'Wonosobo',
  Yahukimo: 'Yahukimo',
  Yalimo: 'Yalimo',
  Yogyakarta: 'Yogyakarta',
}
export const cityObjectIndonisia = {
  AcehBarat: 'Aceh Barat',
  AcehBaratDaya: 'Aceh Barat Daya',
  AcehBesar: 'Aceh Besar',
  AcehJaya: 'Aceh Jaya',
  AcehSelatan: 'Aceh Selatan',
  AcehSingkil: 'Aceh Singkil',
  AcehTamiang: 'Aceh Tamiang',
  AcehTengah: 'Aceh Tengah',
  AcehTenggara: 'Aceh Tenggara',
  AcehTimur: 'Aceh Timur',
  AcehUtara: 'Aceh Utara',
  Agam: 'Agam',
  Alor: 'Alor',
  Ambon: 'Ambon',
  Asahan: 'Asahan',
  Asmat: 'Asmat',
  Badung: 'Badung',
  Balangan: 'Balangan',
  Balikpapan: 'Balikpapan',
  BandaAceh: 'Banda Aceh',
  BandarLampung: 'Bandar Lampung',
  Bandung: 'Bandung',
  BandungBarat: 'Bandung Barat',
  Banggai: 'Banggai',
  BanggaiKepulauan: 'Banggai Kepulauan',
  Bangka: 'Bangka',
  BangkaBarat: 'Bangka Barat',
  BangkaSelatan: 'Bangka Selatan',
  BangkaTengah: 'Bangka Tengah',
  Bangkalan: 'Bangkalan',
  Bangli: 'Bangli',
  Banjar: 'Banjar',
  Banjarbaru: 'Banjarbaru',
  Banjarmasin: 'Banjarmasin',
  Banjarnegara: 'Banjarnegara',
  Bantaeng: 'Bantaeng',
  Bantul: 'Bantul',
  Banyuasin: 'Banyuasin',
  Banyumas: 'Banyumas',
  Banyuwangi: 'Banyuwangi',
  BaritoKuala: 'Barito Kuala',
  BaritoSelatan: 'Barito Selatan',
  BaritoTimur: 'Barito Timur',
  BaritoUtara: 'Barito Utara',
  Barru: 'Barru',
  Batam: 'Batam',
  Batang: 'Batang',
  BatangHari: 'Batang Hari',
  Batu: 'Batu',
  BatuBara: 'Batu Bara',
  Bau: 'Bau',
  Bekasi: 'Bekasi',
  Belitung: 'Belitung',
  BelitungTimur: 'Belitung Timur',
  Belu: 'Belu',
  BenerMeriah: 'Bener Meriah',
  Bengkalis: 'Bengkalis',
  Bengkayang: 'Bengkayang',
  Bengkulu: 'Bengkulu',
  BengkuluSelatan: 'Bengkulu Selatan',
  BengkuluTengah: 'Bengkulu Tengah',
  BengkuluUtara: 'Bengkulu Utara',
  Berau: 'Berau',
  BiakNumfor: 'Biak Numfor',
  Bima: 'Bima',
  Binjai: 'Binjai',
  Bintan: 'Bintan',
  Bireuen: 'Bireuen',
  Bitung: 'Bitung',
  Blitar: 'Blitar',
  Blora: 'Blora',
  Boalemo: 'Boalemo',
  Bogor: 'Bogor',
  Bojonegoro: 'Bojonegoro',
  'BolaangMongondow(Bolmong)': 'Bolaang Mongondow (Bolmong)',
  BolaangMongondowSelatan: 'Bolaang Mongondow Selatan',
  BolaangMongondowTimur: 'Bolaang Mongondow Timur',
  BolaangMongondowUtara: 'Bolaang Mongondow Utara',
  Bombana: 'Bombana',
  Bondowoso: 'Bondowoso',
  Bone: 'Bone',
  BoneBolango: 'Bone Bolango',
  Bontang: 'Bontang',
  BovenDigoel: 'Boven Digoel',
  Boyolali: 'Boyolali',
  Brebes: 'Brebes',
  Bukittinggi: 'Bukittinggi',
  Buleleng: 'Buleleng',
  Bulukumba: 'Bulukumba',
  'Bulungan(Bulongan)': 'Bulungan (Bulongan)',
  Bungo: 'Bungo',
  Buol: 'Buol',
  Buru: 'Buru',
  BuruSelatan: 'Buru Selatan',
  Buton: 'Buton',
  ButonUtara: 'Buton Utara',
  Ciamis: 'Ciamis',
  Cianjur: 'Cianjur',
  Cilacap: 'Cilacap',
  Cilegon: 'Cilegon',
  Cimahi: 'Cimahi',
  Cirebon: 'Cirebon',
  Dairi: 'Dairi',
  'Deiyai(Deliyai)': 'Deiyai (Deliyai)',
  DeliSerdang: 'Deli Serdang',
  Demak: 'Demak',
  Denpasar: 'Denpasar',
  Depok: 'Depok',
  Dharmasraya: 'Dharmasraya',
  Dogiyai: 'Dogiyai',
  Dompu: 'Dompu',
  Donggala: 'Donggala',
  Dumai: 'Dumai',
  EmpatLawang: 'Empat Lawang',
  Ende: 'Ende',
  Enrekang: 'Enrekang',
  Fakfak: 'Fakfak',
  FloresTimur: 'Flores Timur',
  Garut: 'Garut',
  GayoLues: 'Gayo Lues',
  Gianyar: 'Gianyar',
  Gorontalo: 'Gorontalo',
  GorontaloUtara: 'Gorontalo Utara',
  Gowa: 'Gowa',
  Gresik: 'Gresik',
  Grobogan: 'Grobogan',
  GunungKidul: 'Gunung Kidul',
  GunungMas: 'Gunung Mas',
  Gunungsitoli: 'Gunungsitoli',
  HalmaheraBarat: 'Halmahera Barat',
  HalmaheraSelatan: 'Halmahera Selatan',
  HalmaheraTengah: 'Halmahera Tengah',
  HalmaheraTimur: 'Halmahera Timur',
  HalmaheraUtara: 'Halmahera Utara',
  HuluSungaiSelatan: 'Hulu Sungai Selatan',
  HuluSungaiTengah: 'Hulu Sungai Tengah',
  HuluSungaiUtara: 'Hulu Sungai Utara',
  HumbangHasundutan: 'Humbang Hasundutan',
  IndragiriHilir: 'Indragiri Hilir',
  IndragiriHulu: 'Indragiri Hulu',
  Indramayu: 'Indramayu',
  IntanJaya: 'Intan Jaya',
  JakartaBarat: 'Jakarta Barat',
  JakartaPusat: 'Jakarta Pusat',
  JakartaSelatan: 'Jakarta Selatan',
  JakartaTimur: 'Jakarta Timur',
  JakartaUtara: 'Jakarta Utara',
  Jambi: 'Jambi',
  Jayapura: 'Jayapura',
  Jayawijaya: 'Jayawijaya',
  Jember: 'Jember',
  Jembrana: 'Jembrana',
  Jeneponto: 'Jeneponto',
  Jepara: 'Jepara',
  Jombang: 'Jombang',
  Kaimana: 'Kaimana',
  Kampar: 'Kampar',
  Kapuas: 'Kapuas',
  KapuasHulu: 'Kapuas Hulu',
  Karanganyar: 'Karanganyar',
  Karangasem: 'Karangasem',
  Karawang: 'Karawang',
  Karimun: 'Karimun',
  Karo: 'Karo',
  Katingan: 'Katingan',
  Kaur: 'Kaur',
  KayongUtara: 'Kayong Utara',
  Kebumen: 'Kebumen',
  Kediri: 'Kediri',
  Keerom: 'Keerom',
  Kendal: 'Kendal',
  Kendari: 'Kendari',
  Kepahiang: 'Kepahiang',
  KepulauanAnambas: 'Kepulauan Anambas',
  KepulauanAru: 'Kepulauan Aru',
  KepulauanMentawai: 'Kepulauan Mentawai',
  KepulauanMeranti: 'Kepulauan Meranti',
  KepulauanSangihe: 'Kepulauan Sangihe',
  KepulauanSeribu: 'Kepulauan Seribu',
  'KepulauanSiauTagulandangBiaro(Sitaro)':
    'Kepulauan Siau Tagulandang Biaro (Sitaro)',
  KepulauanSula: 'Kepulauan Sula',
  KepulauanTalaud: 'Kepulauan Talaud',
  'KepulauanYapen(YapenWaropen)': 'Kepulauan Yapen (Yapen Waropen)',
  Kerinci: 'Kerinci',
  Ketapang: 'Ketapang',
  Klaten: 'Klaten',
  Klungkung: 'Klungkung',
  Kolaka: 'Kolaka',
  KolakaUtara: 'Kolaka Utara',
  Konawe: 'Konawe',
  KonaweSelatan: 'Konawe Selatan',
  KonaweUtara: 'Konawe Utara',
  Kotabaru: 'Kotabaru',
  Kotamobagu: 'Kotamobagu',
  KotawaringinBarat: 'Kotawaringin Barat',
  KotawaringinTimur: 'Kotawaringin Timur',
  KuantanSingingi: 'Kuantan Singingi',
  KubuRaya: 'Kubu Raya',
  Kudus: 'Kudus',
  KulonProgo: 'Kulon Progo',
  Kuningan: 'Kuningan',
  Kupang: 'Kupang',
  KutaiBarat: 'Kutai Barat',
  KutaiKartanegara: 'Kutai Kartanegara',
  KutaiTimur: 'Kutai Timur',
  LabuhanBatu: 'Labuhan Batu',
  LabuhanBatuSelatan: 'Labuhan Batu Selatan',
  LabuhanBatuUtara: 'Labuhan Batu Utara',
  Lahat: 'Lahat',
  Lamandau: 'Lamandau',
  Lamongan: 'Lamongan',
  LampungBarat: 'Lampung Barat',
  LampungSelatan: 'Lampung Selatan',
  LampungTengah: 'Lampung Tengah',
  LampungTimur: 'Lampung Timur',
  LampungUtara: 'Lampung Utara',
  Landak: 'Landak',
  Langkat: 'Langkat',
  Langsa: 'Langsa',
  LannyJaya: 'Lanny Jaya',
  Lebak: 'Lebak',
  Lebong: 'Lebong',
  Lembata: 'Lembata',
  Lhokseumawe: 'Lhokseumawe',
  LimaPuluhKoto: 'Lima Puluh Koto',
  Lingga: 'Lingga',
  LombokBarat: 'Lombok Barat',
  LombokTengah: 'Lombok Tengah',
  LombokTimur: 'Lombok Timur',
  LombokUtara: 'Lombok Utara',
  LubukLinggau: 'Lubuk Linggau',
  Lumajang: 'Lumajang',
  Luwu: 'Luwu',
  LuwuTimur: 'Luwu Timur',
  LuwuUtara: 'Luwu Utara',
  Madiun: 'Madiun',
  Magelang: 'Magelang',
  Magetan: 'Magetan',
  Majalengka: 'Majalengka',
  Majene: 'Majene',
  Makassar: 'Makassar',
  Malang: 'Malang',
  Malinau: 'Malinau',
  MalukuBaratDaya: 'Maluku Barat Daya',
  MalukuTengah: 'Maluku Tengah',
  MalukuTenggara: 'Maluku Tenggara',
  MalukuTenggaraBarat: 'Maluku Tenggara Barat',
  Mamasa: 'Mamasa',
  MamberamoRaya: 'Mamberamo Raya',
  MamberamoTengah: 'Mamberamo Tengah',
  Mamuju: 'Mamuju',
  MamujuUtara: 'Mamuju Utara',
  Manado: 'Manado',
  MandailingNatal: 'Mandailing Natal',
  Manggarai: 'Manggarai',
  ManggaraiBarat: 'Manggarai Barat',
  ManggaraiTimur: 'Manggarai Timur',
  Manokwari: 'Manokwari',
  ManokwariSelatan: 'Manokwari Selatan',
  Mappi: 'Mappi',
  Maros: 'Maros',
  Mataram: 'Mataram',
  Maybrat: 'Maybrat',
  Medan: 'Medan',
  Melawi: 'Melawi',
  Merangin: 'Merangin',
  Merauke: 'Merauke',
  Mesuji: 'Mesuji',
  Metro: 'Metro',
  Mimika: 'Mimika',
  Minahasa: 'Minahasa',
  MinahasaSelatan: 'Minahasa Selatan',
  MinahasaTenggara: 'Minahasa Tenggara',
  MinahasaUtara: 'Minahasa Utara',
  Mojokerto: 'Mojokerto',
  Morowali: 'Morowali',
  MuaraEnim: 'Muara Enim',
  MuaroJambi: 'Muaro Jambi',
  MukoMuko: 'Muko Muko',
  Muna: 'Muna',
  MurungRaya: 'Murung Raya',
  MusiBanyuasin: 'Musi Banyuasin',
  MusiRawas: 'Musi Rawas',
  Nabire: 'Nabire',
  NaganRaya: 'Nagan Raya',
  Nagekeo: 'Nagekeo',
  Natuna: 'Natuna',
  Nduga: 'Nduga',
  Ngada: 'Ngada',
  Nganjuk: 'Nganjuk',
  Ngawi: 'Ngawi',
  Nias: 'Nias',
  NiasBarat: 'Nias Barat',
  NiasSelatan: 'Nias Selatan',
  NiasUtara: 'Nias Utara',
  Nunukan: 'Nunukan',
  OganIlir: 'Ogan Ilir',
  OganKomeringIlir: 'Ogan Komering Ilir',
  OganKomeringUlu: 'Ogan Komering Ulu',
  OganKomeringUluSelatan: 'Ogan Komering Ulu Selatan',
  OganKomeringUluTimur: 'Ogan Komering Ulu Timur',
  Pacitan: 'Pacitan',
  Padang: 'Padang',
  PadangLawas: 'Padang Lawas',
  PadangLawasUtara: 'Padang Lawas Utara',
  PadangPanjang: 'Padang Panjang',
  PadangPariaman: 'Padang Pariaman',
  PadangSidempuan: 'Padang Sidempuan',
  PagarAlam: 'Pagar Alam',
  PakpakBharat: 'Pakpak Bharat',
  PalangkaRaya: 'Palangka Raya',
  Palembang: 'Palembang',
  Palopo: 'Palopo',
  Palu: 'Palu',
  Pamekasan: 'Pamekasan',
  Pandeglang: 'Pandeglang',
  Pangandaran: 'Pangandaran',
  PangkajeneKepulauan: 'Pangkajene Kepulauan',
  PangkalPinang: 'Pangkal Pinang',
  Paniai: 'Paniai',
  Parepare: 'Parepare',
  Pariaman: 'Pariaman',
  ParigiMoutong: 'Parigi Moutong',
  Pasaman: 'Pasaman',
  PasamanBarat: 'Pasaman Barat',
  Paser: 'Paser',
  Pasuruan: 'Pasuruan',
  Pati: 'Pati',
  Payakumbuh: 'Payakumbuh',
  PegununganArfak: 'Pegunungan Arfak',
  PegununganBintang: 'Pegunungan Bintang',
  Pekalongan: 'Pekalongan',
  Pekanbaru: 'Pekanbaru',
  Pelalawan: 'Pelalawan',
  Pemalang: 'Pemalang',
  PematangSiantar: 'Pematang Siantar',
  PenajamPaserUtara: 'Penajam Paser Utara',
  Pesawaran: 'Pesawaran',
  PesisirBarat: 'Pesisir Barat',
  PesisirSelatan: 'Pesisir Selatan',
  Pidie: 'Pidie',
  PidieJaya: 'Pidie Jaya',
  Pinrang: 'Pinrang',
  Pohuwato: 'Pohuwato',
  PolewaliMandar: 'Polewali Mandar',
  Ponorogo: 'Ponorogo',
  Pontianak: 'Pontianak',
  Poso: 'Poso',
  Prabumulih: 'Prabumulih',
  Pringsewu: 'Pringsewu',
  Probolinggo: 'Probolinggo',
  PulangPisau: 'Pulang Pisau',
  PulauMorotai: 'Pulau Morotai',
  Puncak: 'Puncak',
  PuncakJaya: 'Puncak Jaya',
  Purbalingga: 'Purbalingga',
  Purwakarta: 'Purwakarta',
  Purworejo: 'Purworejo',
  RajaAmpat: 'Raja Ampat',
  RejangLebong: 'Rejang Lebong',
  Rembang: 'Rembang',
  RokanHilir: 'Rokan Hilir',
  RokanHulu: 'Rokan Hulu',
  RoteNdao: 'Rote Ndao',
  Sabang: 'Sabang',
  SabuRaijua: 'Sabu Raijua',
  Salatiga: 'Salatiga',
  Samarinda: 'Samarinda',
  Sambas: 'Sambas',
  Samosir: 'Samosir',
  Sampang: 'Sampang',
  Sanggau: 'Sanggau',
  Sarmi: 'Sarmi',
  Sarolangun: 'Sarolangun',
  SawahLunto: 'Sawah Lunto',
  Sekadau: 'Sekadau',
  'Selayar(KepulauanSelayar)': 'Selayar (Kepulauan Selayar)',
  Seluma: 'Seluma',
  Semarang: 'Semarang',
  SeramBagianBarat: 'Seram Bagian Barat',
  SeramBagianTimur: 'Seram Bagian Timur',
  Serang: 'Serang',
  SerdangBedagai: 'Serdang Bedagai',
  Seruyan: 'Seruyan',
  Siak: 'Siak',
  Sibolga: 'Sibolga',
  SidenrengRappang: 'Sidenreng Rappang',
  Sidoarjo: 'Sidoarjo',
  Sigi: 'Sigi',
  'Sijunjung(SawahLuntoSijunjung)': 'Sijunjung (Sawah Lunto Sijunjung)',
  Sikka: 'Sikka',
  Simalungun: 'Simalungun',
  Simeulue: 'Simeulue',
  Singkawang: 'Singkawang',
  Sinjai: 'Sinjai',
  Sintang: 'Sintang',
  Situbondo: 'Situbondo',
  Sleman: 'Sleman',
  Solok: 'Solok',
  SolokSelatan: 'Solok Selatan',
  Soppeng: 'Soppeng',
  Sorong: 'Sorong',
  SorongSelatan: 'Sorong Selatan',
  Sragen: 'Sragen',
  Subang: 'Subang',
  Subulussalam: 'Subulussalam',
  Sukabumi: 'Sukabumi',
  Sukamara: 'Sukamara',
  Sukoharjo: 'Sukoharjo',
  SumbaBarat: 'Sumba Barat',
  SumbaBaratDaya: 'Sumba Barat Daya',
  SumbaTengah: 'Sumba Tengah',
  SumbaTimur: 'Sumba Timur',
  Sumbawa: 'Sumbawa',
  SumbawaBarat: 'Sumbawa Barat',
  Sumedang: 'Sumedang',
  Sumenep: 'Sumenep',
  Sungaipenuh: 'Sungaipenuh',
  Supiori: 'Supiori',
  Surabaya: 'Surabaya',
  'Surakarta(Solo)': 'Surakarta (Solo)',
  Tabalong: 'Tabalong',
  Tabanan: 'Tabanan',
  Takalar: 'Takalar',
  Tambrauw: 'Tambrauw',
  TanaTidung: 'Tana Tidung',
  TanaToraja: 'Tana Toraja',
  TanahBumbu: 'Tanah Bumbu',
  TanahDatar: 'Tanah Datar',
  TanahLaut: 'Tanah Laut',
  Tangerang: 'Tangerang',
  TangerangSelatan: 'Tangerang Selatan',
  Tanggamus: 'Tanggamus',
  TanjungBalai: 'Tanjung Balai',
  TanjungJabungBarat: 'Tanjung Jabung Barat',
  TanjungJabungTimur: 'Tanjung Jabung Timur',
  TanjungPinang: 'Tanjung Pinang',
  TapanuliSelatan: 'Tapanuli Selatan',
  TapanuliTengah: 'Tapanuli Tengah',
  TapanuliUtara: 'Tapanuli Utara',
  Tapin: 'Tapin',
  Tarakan: 'Tarakan',
  Tasikmalaya: 'Tasikmalaya',
  TebingTinggi: 'Tebing Tinggi',
  Tebo: 'Tebo',
  Tegal: 'Tegal',
  TelukBintuni: 'Teluk Bintuni',
  TelukWondama: 'Teluk Wondama',
  Temanggung: 'Temanggung',
  Ternate: 'Ternate',
  TidoreKepulauan: 'Tidore Kepulauan',
  TimorTengahSelatan: 'Timor Tengah Selatan',
  TimorTengahUtara: 'Timor Tengah Utara',
  TobaSamosir: 'Toba Samosir',
  TojoUna: 'Tojo Una',
  Toli: 'Toli',
  Tolikara: 'Tolikara',
  Tomohon: 'Tomohon',
  TorajaUtara: 'Toraja Utara',
  Trenggalek: 'Trenggalek',
  Tual: 'Tual',
  Tuban: 'Tuban',
  TulangBawang: 'Tulang Bawang',
  TulangBawangBarat: 'Tulang Bawang Barat',
  Tulungagung: 'Tulungagung',
  Wajo: 'Wajo',
  Wakatobi: 'Wakatobi',
  Waropen: 'Waropen',
  WayKanan: 'Way Kanan',
  Wonogiri: 'Wonogiri',
  Wonosobo: 'Wonosobo',
  Yahukimo: 'Yahukimo',
  Yalimo: 'Yalimo',
  Yogyakarta: 'Yogyakarta',
}
export const cityList = [
  'ACEH BARAT',
  'ACEH BARAT DAYA',
  'ACEH BESAR',
  'ACEH JAYA',
  'ACEH SELATAN',
  'ACEH SINGKIL',
  'ACEH TAMIANG',
  'ACEH TENGAH',
  'ACEH TENGGARA',
  'ACEH TIMUR',
  'ACEH UTARA',
  'AGAM',
  'AMBON',
  'ASAHAN',
  'BADUNG',
  'BALANGAN',
  'BALIKPAPAN',
  'BANDA ACEH',
  'BANDAR LAMPUNG',
  'BANDUNG',
  'BANDUNG BARAT',
  'BANGGAI',
  'BANGGAI KEPULAUAN',
  'BANGKA',
  'BANGKA BARAT',
  'BANGKA SELATAN',
  'BANGKA TENGAH',
  'BANGKALAN',
  'BANGLI',
  'BANJAR',
  'BANJARBARU',
  'BANJARMASIN',
  'BANJARNEGARA',
  'BANTAENG',
  'BANTUL',
  'BANYUASIN',
  'BANYUMAS',
  'BANYUWANGI',
  'BARITO KUALA',
  'BARITO SELATAN',
  'BARITO TIMUR',
  'BARITO UTARA',
  'BARRU',
  'BATAM',
  'BATANG',
  'BATANG HARI',
  'BATU',
  'BATU BARA',
  'BAU-BAU',
  'BEKASI',
  'BELITUNG',
  'BELITUNG TIMUR',
  'BENER MERIAH',
  'BENGKALIS',
  'BENGKAYANG',
  'BENGKULU',
  'BENGKULU SELATAN',
  'BENGKULU TENGAH',
  'BENGKULU UTARA',
  'BERAU',
  'BIAK NUMFOR',
  'BIMA',
  'BINJAI',
  'BINTAN',
  'BIREUEN',
  'BITUNG',
  'BLITAR',
  'BLORA',
  'BOALEMO',
  'BOGOR',
  'BOJONEGORO',
  'BOLAANG MONGONDOW BOLMONG',
  'BOLAANG MONGONDOW SELATAN',
  'BOLAANG MONGONDOW TIMUR',
  'BOLAANG MONGONDOW UTARA',
  'BOMBANA',
  'BONDOWOSO',
  'BONE',
  'BONE BOLANGO',
  'BONTANG',
  'BOVEN DIGOEL',
  'BOYOLALI',
  'BREBES',
  'BUKITTINGGI',
  'BULELENG',
  'BULUKUMBA',
  'BULUNGAN BULONGAN',
  'BUNGO',
  'BUOL',
  'BURU SELATAN',
  'BUTON',
  'BUTON UTARA',
  'CIAMIS',
  'CIANJUR',
  'CILACAP',
  'CILEGON',
  'CIMAHI',
  'CIREBON',
  'DAIRI',
  'DELI SERDANG',
  'DEMAK',
  'DENPASAR',
  'DEPOK',
  'DHARMASRAYA',
  'DOGIYAI',
  'DOMPU',
  'DONGGALA',
  'DUMAI',
  'EMPAT LAWANG',
  'ENDE',
  'ENREKANG',
  'FAKFAK',
  'GARUT',
  'GAYO LUES',
  'GIANYAR',
  'GORONTALO',
  'GORONTALO UTARA',
  'GOWA',
  'GRESIK',
  'GROBOGAN',
  'GUNUNG KIDUL',
  'GUNUNG MAS',
  'GUNUNGSITOLI',
  'HULU SUNGAI SELATAN',
  'HULU SUNGAI TENGAH',
  'HULU SUNGAI UTARA',
  'HUMBANG HASUNDUTAN',
  'INDRAGIRI HILIR',
  'INDRAGIRI HULU',
  'INDRAMAYU',
  'JAKARTA BARAT',
  'JAKARTA PUSAT',
  'JAKARTA SELATAN',
  'JAKARTA TIMUR',
  'JAKARTA UTARA',
  'JAMBI',
  'JAYAPURA',
  'JAYAWIJAYA',
  'JEMBER',
  'JEMBRANA',
  'JENEPONTO',
  'JEPARA',
  'JOMBANG',
  'KAMPAR',
  'KAPUAS',
  'KAPUAS HULU',
  'KARANGANYAR',
  'KARANGASEM',
  'KARAWANG',
  'KARIMUN',
  'KARO',
  'KATINGAN',
  'KAUR',
  'KAYONG UTARA',
  'KEBUMEN',
  'KEDIRI',
  'KEEROM',
  'KENDAL',
  'KENDARI',
  'KEPAHIANG',
  'KEPULAUAN ANAMBAS',
  'KEPULAUAN ARU',
  'KEPULAUAN MENTAWAI',
  'KEPULAUAN MERANTI',
  'KEPULAUAN SANGIHE',
  'KEPULAUAN SERIBU',
  'KEPULAUAN SIAU TAGULANDANG BIARO SITARO',
  'KEPULAUAN TALAUD',
  'KEPULAUAN YAPEN YAPEN WAROPEN',
  'KERINCI',
  'KETAPANG',
  'KLATEN',
  'KLUNGKUNG',
  'KOLAKA',
  'KOLAKA UTARA',
  'KONAWE',
  'KONAWE SELATAN',
  'KONAWE UTARA',
  'KOTABARU',
  'KOTAMOBAGU',
  'KOTAWARINGIN BARAT',
  'KOTAWARINGIN TIMUR',
  'KUANTAN SINGINGI',
  'KUBU RAYA',
  'KUDUS',
  'KULON PROGO',
  'KUNINGAN',
  'KUPANG',
  'KUTAI BARAT',
  'KUTAI KARTANEGARA',
  'KUTAI TIMUR',
  'LABUHAN BATU',
  'LABUHAN BATU SELATAN',
  'LABUHAN BATU UTARA',
  'LAHAT',
  'LAMANDAU',
  'LAMONGAN',
  'LAMPUNG BARAT',
  'LAMPUNG SELATAN',
  'LAMPUNG TENGAH',
  'LAMPUNG TIMUR',
  'LAMPUNG UTARA',
  'LANDAK',
  'LANGKAT',
  'LANGSA',
  'LEBAK',
  'LEBONG',
  'LHOKSEUMAWE',
  'LIMA PULUH KOTO/KOTA',
  'LINGGA',
  'LOMBOK BARAT',
  'LOMBOK TENGAH',
  'LOMBOK TIMUR',
  'LOMBOK UTARA',
  'LUBUK LINGGAU',
  'LUMAJANG',
  'LUWU',
  'LUWU TIMUR',
  'LUWU UTARA',
  'MADIUN',
  'MAGELANG',
  'MAGETAN',
  'MAJALENGKA',
  'MAJENE',
  'MAKASSAR',
  'MALANG',
  'MALINAU',
  'MALUKU TENGAH',
  'MALUKU TENGGARA',
  'MAMASA',
  'MAMUJU',
  'MAMUJU UTARA',
  'MANADO',
  'MANDAILING NATAL',
  'MANOKWARI',
  'MAROS',
  'MATARAM',
  'MEDAN',
  'MELAWI',
  'MERANGIN',
  'MERAUKE',
  'MESUJI',
  'METRO',
  'MIMIKA',
  'MINAHASA',
  'MINAHASA SELATAN',
  'MINAHASA TENGGARA',
  'MINAHASA UTARA',
  'MOJOKERTO',
  'MOROWALI',
  'MUARA ENIM',
  'MUARO JAMBI',
  'MUKO MUKO',
  'MUNA',
  'MURUNG RAYA',
  'MUSI BANYUASIN',
  'MUSI RAWAS',
  'NABIRE',
  'NAGAN RAYA',
  'NDUGA',
  'NGANJUK',
  'NGAWI',
  'NIAS',
  'NIAS BARAT',
  'NIAS SELATAN',
  'NIAS UTARA',
  'NUNUKAN',
  'OGAN ILIR',
  'OGAN KOMERING ILIR',
  'OGAN KOMERING ULU',
  'OGAN KOMERING ULU SELATAN',
  'OGAN KOMERING ULU TIMUR',
  'OTHERS',
  'PACITAN',
  'PADANG',
  'PADANG LAWAS',
  'PADANG LAWAS UTARA',
  'PADANG PANJANG',
  'PADANG PARIAMAN',
  'PADANG SIDEMPUAN',
  'PAGAR ALAM',
  'PAKPAK BHARAT',
  'PALANGKA RAYA',
  'PALEMBANG',
  'PALOPO',
  'PALU',
  'PAMEKASAN',
  'PANDEGLANG',
  'PANGANDARAN',
  'PANGKAJENE KEPULAUAN',
  'PANGKAL PINANG',
  'PAREPARE',
  'PARIAMAN',
  'PARIGI MOUTONG',
  'PASAMAN',
  'PASAMAN BARAT',
  'PASER',
  'PASURUAN',
  'PATI',
  'PAYAKUMBUH',
  'PEKALONGAN',
  'PEKANBARU',
  'PELALAWAN',
  'PEMALANG',
  'PEMATANG SIANTAR',
  'PENAJAM PASER UTARA',
  'PESAWARAN',
  'PESISIR BARAT',
  'PESISIR SELATAN',
  'PIDIE',
  'PIDIE JAYA',
  'PINRANG',
  'POHUWATO',
  'POLEWALI MANDAR',
  'PONOROGO',
  'PONTIANAK',
  'POSO',
  'PRABUMULIH',
  'PRINGSEWU',
  'PROBOLINGGO',
  'PULANG PISAU',
  'PULAU MOROTAI',
  'PURBALINGGA',
  'PURWAKARTA',
  'PURWOREJO',
  'REJANG LEBONG',
  'REMBANG',
  'ROKAN HILIR',
  'ROKAN HULU',
  'SABANG',
  'SALATIGA',
  'SAMARINDA',
  'SAMBAS',
  'SAMOSIR',
  'SAMPANG',
  'SANGGAU',
  'SARMI',
  'SAROLANGUN',
  'SAWAH LUNTO',
  'SEKADAU',
  'SELAYAR KEPULAUAN SELAYAR',
  'SELUMA',
  'SEMARANG',
  'SERAM BAGIAN BARAT',
  'SERANG',
  'SERDANG BEDAGAI',
  'SERUYAN',
  'SIAK',
  'SIBOLGA',
  'SIDENRENG RAPPANG/RAPANG',
  'SIDOARJO',
  'SIGI',
  'SIJUNJUNG SAWAH LUNTO SIJUNJUNG',
  'SIMALUNGUN',
  'SIMEULUE',
  'SINGKAWANG',
  'SINJAI',
  'SINTANG',
  'SITUBONDO',
  'SLEMAN',
  'SOLOK',
  'SOLOK SELATAN',
  'SOPPENG',
  'SORONG',
  'SRAGEN',
  'SUBANG',
  'SUBULUSSALAM',
  'SUKABUMI',
  'SUKAMARA',
  'SUKOHARJO',
  'SUMBA BARAT DAYA',
  'SUMBAWA',
  'SUMEDANG',
  'SUMENEP',
  'SUNGAIPENUH',
  'SURABAYA',
  'SURAKARTA SOLO',
  'TABALONG',
  'TABANAN',
  'TAKALAR',
  'TANA TIDUNG',
  'TANA TORAJA',
  'TANAH BUMBU',
  'TANAH DATAR',
  'TANAH LAUT',
  'TANGERANG',
  'TANGERANG SELATAN',
  'TANGGAMUS',
  'TANJUNG BALAI',
  'TANJUNG JABUNG BARAT',
  'TANJUNG JABUNG TIMUR',
  'TANJUNG PINANG',
  'TAPANULI SELATAN',
  'TAPANULI TENGAH',
  'TAPANULI UTARA',
  'TAPIN',
  'TARAKAN',
  'TASIKMALAYA',
  'TEBING TINGGI',
  'TEBO',
  'TEGAL',
  'TELUK BINTUNI',
  'TEMANGGUNG',
  'TERNATE',
  'TIMOR TENGAH UTARA',
  'TOBA SAMOSIR',
  'TOJO UNA-UNA',
  'TOLI-TOLI',
  'TOMOHON',
  'TORAJA UTARA',
  'TRENGGALEK',
  'TUBAN',
  'TULANG BAWANG',
  'TULANG BAWANG BARAT',
  'TULUNGAGUNG',
  'WAJO',
  'WAKATOBI',
  'WAY KANAN',
  'WONOGIRI',
  'WONOSOBO',
  'YOGYAKARTA',
]
export const uppperCaseCityList = [
  'Badung',
  'Bangli',
  'Buleleng',
  'Denpasar',
  'Gianyar',
  'Jembrana',
  'Karangasem',
  'Klungkung',
  'Tabanan',
  'Bangka Barat',
  'Bangka Selatan',
  'Bangka Tengah',
  'Bangka',
  'Belitung Timur',
  'Belitung',
  'Pangkal Pinang',
  'Cilegon',
  'Lebak',
  'Pandeglang',
  'Serang',
  'Tangerang Selatan',
  'Tangerang',
  'Bengkulu Selatan',
  'Bengkulu Tengah',
  'Bengkulu Utara',
  'Bengkulu',
  'Kaur',
  'Kepahiang',
  'Lebong',
  'Muko Muko',
  'Rejang Lebong',
  'Seluma',
  'Bantul',
  'Gunung Kidul',
  'Kulon Progo',
  'Sleman',
  'Yogyakarta',
  'Jakarta Barat',
  'Jakarta Pusat',
  'Jakarta Selatan',
  'Jakarta Timur',
  'Jakarta Utara',
  'Kepulauan Seribu',
  'Boalemo',
  'Bone Bolango',
  'Gorontalo Utara',
  'Gorontalo',
  'Pohuwato',
  'Batang Hari',
  'Bungo',
  'Jambi',
  'Kerinci',
  'Merangin',
  'Muaro Jambi',
  'Sarolangun',
  'Sungaipenuh',
  'Tanjung Jabung Barat',
  'Tanjung Jabung Timur',
  'Tebo',
  'Bandung Barat',
  'Bandung',
  'Banjar',
  'Bekasi',
  'Bogor',
  'Ciamis',
  'Cianjur',
  'Cimahi',
  'Cirebon',
  'Depok',
  'Garut',
  'Indramayu',
  'Karawang',
  'Kuningan',
  'Majalengka',
  'Pangandaran',
  'Purwakarta',
  'Subang',
  'Sukabumi',
  'Sumedang',
  'Tasikmalaya',
  'Banjarnegara',
  'Banyumas',
  'Batang',
  'Blora',
  'Boyolali',
  'Brebes',
  'Cilacap',
  'Demak',
  'Grobogan',
  'Jepara',
  'Karanganyar',
  'Kebumen',
  'Kendal',
  'Klaten',
  'Kudus',
  'Magelang',
  'Pati',
  'Pekalongan',
  'Pemalang',
  'Purbalingga',
  'Purworejo',
  'Rembang',
  'Salatiga',
  'Semarang',
  'Sragen',
  'Sukoharjo',
  'Surakarta (solo)',
  'Tegal',
  'Temanggung',
  'Wonogiri',
  'Wonosobo',
  'Bangkalan',
  'Banyuwangi',
  'Batu',
  'Blitar',
  'Bojonegoro',
  'Bondowoso',
  'Gresik',
  'Jember',
  'Jombang',
  'Kediri',
  'Lamongan',
  'Lumajang',
  'Madiun',
  'Magetan',
  'Malang',
  'Mojokerto',
  'Nganjuk',
  'Ngawi',
  'Pacitan',
  'Pamekasan',
  'Pasuruan',
  'Ponorogo',
  'Probolinggo',
  'Sampang',
  'Sidoarjo',
  'Situbondo',
  'Sumenep',
  'Surabaya',
  'Trenggalek',
  'Tuban',
  'Tulungagung',
  'Bengkayang',
  'Kapuas Hulu',
  'Kayong Utara',
  'Ketapang',
  'Kubu Raya',
  'Landak',
  'Melawi',
  'Pontianak',
  'Sambas',
  'Sanggau',
  'Sekadau',
  'Singkawang',
  'Sintang',
  'Balangan',
  'Banjar',
  'Banjarbaru',
  'Banjarmasin',
  'Barito Kuala',
  'Hulu Sungai Selatan',
  'Hulu Sungai Tengah',
  'Hulu Sungai Utara',
  'Kotabaru',
  'Tabalong',
  'Tanah Bumbu',
  'Tanah Laut',
  'Tapin',
  'Barito Selatan',
  'Barito Timur',
  'Barito Utara',
  'Gunung Mas',
  'Kapuas',
  'Katingan',
  'Kotawaringin Barat',
  'Kotawaringin Timur',
  'Lamandau',
  'Murung Raya',
  'Palangka Raya',
  'Pulang Pisau',
  'Seruyan',
  'Sukamara',
  'Balikpapan',
  'Berau',
  'Bontang',
  'Kutai Barat',
  'Kutai Kartanegara',
  'Kutai Timur',
  'Paser',
  'Penajam Paser Utara',
  'Samarinda',
  'Bulungan (bulongan)',
  'Malinau',
  'Nunukan',
  'Tana Tidung',
  'Tarakan',
  'Batam',
  'Bintan',
  'Karimun',
  'Kepulauan Anambas',
  'Lingga',
  'Natuna',
  'Tanjung Pinang',
  'Bandar Lampung',
  'Lampung Barat',
  'Lampung Selatan',
  'Lampung Tengah',
  'Lampung Timur',
  'Lampung Utara',
  'Mesuji',
  'Metro',
  'Pesawaran',
  'Pesisir Barat',
  'Pringsewu',
  'Tanggamus',
  'Tulang Bawang Barat',
  'Tulang Bawang',
  'Way Kanan',
  'Halmahera Barat',
  'Halmahera Selatan',
  'Halmahera Tengah',
  'Halmahera Timur',
  'Halmahera Utara',
  'Kepulauan Sula',
  'Pulau Morotai',
  'Ternate',
  'Tidore Kepulauan',
  'Ambon',
  'Buru Selatan',
  'Buru',
  'Kepulauan Aru',
  'Maluku Barat Daya',
  'Maluku Tengah',
  'Maluku Tenggara Barat',
  'Maluku Tenggara',
  'Seram Bagian Barat',
  'Seram Bagian Timur',
  'Tual',
  'Aceh Barat Daya',
  'Aceh Barat',
  'Aceh Besar',
  'Aceh Jaya',
  'Aceh Selatan',
  'Aceh Singkil',
  'Aceh Tamiang',
  'Aceh Tengah',
  'Aceh Tenggara',
  'Aceh Timur',
  'Aceh Utara',
  'Banda Aceh',
  'Bener Meriah',
  'Bireuen',
  'Gayo Lues',
  'Langsa',
  'Lhokseumawe',
  'Nagan Raya',
  'Pidie Jaya',
  'Pidie',
  'Sabang',
  'Simeulue',
  'Subulussalam',
  'Bima',
  'Dompu',
  'Lombok Barat',
  'Lombok Tengah',
  'Lombok Timur',
  'Lombok Utara',
  'Mataram',
  'Sumbawa Barat',
  'Sumbawa',
  'Alor',
  'Belu',
  'Ende',
  'Flores Timur',
  'Kupang',
  'Lembata',
  'Manggarai Barat',
  'Manggarai Timur',
  'Manggarai',
  'Nagekeo',
  'Ngada',
  'Rote Ndao',
  'Sabu Raijua',
  'Sikka',
  'Sumba Barat Daya',
  'Sumba Barat',
  'Sumba Tengah',
  'Sumba Timur',
  'Timor Tengah Selatan',
  'Timor Tengah Utara',
  'Fakfak',
  'Kaimana',
  'Manokwari Selatan',
  'Manokwari',
  'Maybrat',
  'Pegunungan Arfak',
  'Raja Ampat',
  'Sorong Selatan',
  'Sorong',
  'Tambrauw',
  'Teluk Bintuni',
  'Teluk Wondama',
  'Asmat',
  'Biak Numfor',
  'Boven Digoel',
  'Deiyai (deliyai)',
  'Dogiyai',
  'Intan Jaya',
  'Jayapura',
  'Jayawijaya',
  'Keerom',
  'Kepulauan Yapen (yapen Waropen)',
  'Lanny Jaya',
  'Mamberamo Raya',
  'Mamberamo Tengah',
  'Mappi',
  'Merauke',
  'Mimika',
  'Nabire',
  'Nduga',
  'Paniai',
  'Pegunungan Bintang',
  'Puncak Jaya',
  'Puncak',
  'Sarmi',
  'Supiori',
  'Tolikara',
  'Waropen',
  'Yahukimo',
  'Yalimo',
  'Bengkalis',
  'Dumai',
  'Indragiri Hilir',
  'Indragiri Hulu',
  'Kampar',
  'Kepulauan Meranti',
  'Kuantan Singingi',
  'Pekanbaru',
  'Pelalawan',
  'Rokan Hilir',
  'Rokan Hulu',
  'Siak',
  'Majene',
  'Mamasa',
  'Mamuju Utara',
  'Mamuju',
  'Polewali Mandar',
  'Bantaeng',
  'Barru',
  'Bone',
  'Bulukumba',
  'Enrekang',
  'Gowa',
  'Jeneponto',
  'Luwu Timur',
  'Luwu Utara',
  'Luwu',
  'Makassar',
  'Maros',
  'Palopo',
  'Pangkajene Kepulauan',
  'Parepare',
  'Pinrang',
  'Selayar (kepulauan Selayar)',
  'Sidenreng Rappang',
  'Sinjai',
  'Soppeng',
  'Takalar',
  'Tana Toraja',
  'Toraja Utara',
  'Wajo',
  'Banggai Kepulauan',
  'Banggai',
  'Buol',
  'Donggala',
  'Morowali',
  'Palu',
  'Parigi Moutong',
  'Poso',
  'Sigi',
  'Tojo Una',
  'Toli',
  'Bau',
  'Bombana',
  'Buton Utara',
  'Buton',
  'Kendari',
  'Kolaka Utara',
  'Kolaka',
  'Konawe Selatan',
  'Konawe Utara',
  'Konawe',
  'Muna',
  'Wakatobi',
  'Bitung',
  'Bolaang Mongondow (bolmong)',
  'Bolaang Mongondow Selatan',
  'Bolaang Mongondow Timur',
  'Bolaang Mongondow Utara',
  'Kepulauan Sangihe',
  'Kepulauan Siau Tagulandang Biaro (sitaro)',
  'Kepulauan Talaud',
  'Kotamobagu',
  'Manado',
  'Minahasa Selatan',
  'Minahasa Tenggara',
  'Minahasa Utara',
  'Minahasa',
  'Tomohon',
  'Agam',
  'Bukittinggi',
  'Dharmasraya',
  'Kepulauan Mentawai',
  'Lima Puluh Koto',
  'Padang Panjang',
  'Padang Pariaman',
  'Padang',
  'Pariaman',
  'Pasaman Barat',
  'Pasaman',
  'Payakumbuh',
  'Pesisir Selatan',
  'Sawah Lunto',
  'Sijunjung (sawah Lunto Sijunjung)',
  'Solok Selatan',
  'Solok',
  'Tanah Datar',
  'Banyuasin',
  'Empat Lawang',
  'Lahat',
  'Lubuk Linggau',
  'Muara Enim',
  'Musi Banyuasin',
  'Musi Rawas',
  'Ogan Ilir',
  'Ogan Komering Ilir',
  'Ogan Komering Ulu Selatan',
  'Ogan Komering Ulu Timur',
  'Ogan Komering Ulu',
  'Pagar Alam',
  'Palembang',
  'Prabumulih',
  'Asahan',
  'Batu Bara',
  'Binjai',
  'Dairi',
  'Deli Serdang',
  'Gunungsitoli',
  'Humbang Hasundutan',
  'Karo',
  'Labuhan Batu Selatan',
  'Labuhan Batu Utara',
  'Labuhan Batu',
  'Langkat',
  'Mandailing Natal',
  'Medan',
  'Nias Barat',
  'Nias Selatan',
  'Nias Utara',
  'Nias',
  'Padang Lawas Utara',
  'Padang Lawas',
  'Padang Sidempuan',
  'Pakpak Bharat',
  'Pematang Siantar',
  'Samosir',
  'Serdang Bedagai',
  'Sibolga',
  'Simalungun',
  'Tanjung Balai',
  'Tapanuli Selatan',
  'Tapanuli Tengah',
  'Tapanuli Utara',
  'Tebing Tinggi',
  'Toba Samosir',
]
export const cityObjectEnglish = {
  ACEHBARAT: 'West Aceh',
  ACEHBARATDAYA: 'Southwest Aceh',
  ACEHBESAR: 'Aceh Besar',
  ACEHJAYA: 'Aceh Jaya',
  ACEHSELATAN: 'South Aceh',
  ACEHSINGKIL: 'Aceh Singkil',
  ACEHTAMIANG: 'Aceh Tamiang',
  ACEHTENGAH: 'Central Aceh',
  ACEHTENGGARA: 'Southeast Aceh',
  ACEHTIMUR: 'East Aceh',
  ACEHUTARA: 'North Aceh',
  AGAM: 'Agam',
  AMBON: 'Ambon',
  ASAHAN: 'Asahan',
  BADUNG: 'Badung',
  BALANGAN: 'Balangan',
  BALIKPAPAN: 'Balikpapan',
  BANDAACEH: 'Banda Aceh',
  BANDARLAMPUNG: 'Bandar Lampung',
  BANDUNG: 'Bandung',
  BANDUNGBARAT: 'West Bandung',
  BANGGAI: 'Banggai',
  BANGGAIKEPULAUAN: 'Banggai Kepulauan',
  BANGKA: 'Bangka',
  BANGKABARAT: 'West Bangka',
  BANGKALAN: 'Bangkalan',
  BANGKASELATAN: 'South Bangka',
  BANGKATENGAH: 'Central Bangka',
  BANGLI: 'Bangli',
  BANJAR: 'Banjar',
  BANJARBARU: 'Banjarbaru',
  BANJARMASIN: 'Banjarmasin',
  BANJARNEGARA: 'Banjarnegara',
  BANTAENG: 'Bantaeng',
  BANTUL: 'Bantul',
  BANYUASIN: 'Banyuasin',
  BANYUMAS: 'Banyumas',
  BANYUWANGI: 'Banyuwangi',
  BARITOKUALA: 'Barito Kuala',
  BARITOSELATAN: 'South Barito',
  BARITOTIMUR: 'East Barito',
  BARITOUTARA: 'North Barito',
  BARRU: 'Barru',
  BATAM: 'Batam',
  BATANG: 'Batang',
  BATANGHARI: 'Batang Hari',
  BATU: 'Batu',
  BATUBARA: 'Batu Bara',
  BAUBAU: 'Bau-Bau',
  BEKASI: 'Bekasi',
  BELITUNG: 'Belitung',
  BELITUNGTIMUR: 'East Belitung',
  BENERMERIAH: 'Bener Meriah',
  BENGKALIS: 'Bengkalis',
  BENGKAYANG: 'Bengkayang',
  BENGKULU: 'Bengkulu',
  BENGKULUSELATAN: 'South ',
  BENGKULUTENGAH: 'East Bengkulu',
  BENGKULUUTARA: 'North Bengkulu',
  BERAU: 'Berau',
  BIAKNUMFOR: 'Biak Numfor',
  BIMA: 'Bima',
  BINJAI: 'Binjai',
  BINTAN: 'Bintan',
  BIREUEN: 'Bireuen',
  BITUNG: 'Bitung',
  BLITAR: 'Blitar',
  BLORA: 'Blora',
  BOALEMO: 'Boalemo',
  BOGOR: 'Bogor',
  BOJONEGORO: 'Bojonegoro',
  BOLAANGMONGONDOWBOLMONG: 'Bolaang Mongondow Bolmong',
  BOLAANGMONGONDOWSELATAN: 'South Bolaang Mongondow',
  BOLAANGMONGONDOWTIMUR: 'East Bolaang Mongondow',
  BOLAANGMONGONDOWUTARA: 'North Bolaang Mongondow',
  BOMBANA: 'Bombana',
  BONDOWOSO: 'Bondowoso',
  BONE: 'Bone',
  BONEBOLANGO: 'Bone Bolango',
  BONTANG: 'Bontang',
  BOVENDIGOEL: 'Boven Digoel',
  BOYOLALI: 'Boyolali',
  BREBES: 'Brebes',
  BUKITTINGGI: 'Bukittinggi',
  BULELENG: 'Buleleng',
  BULUKUMBA: 'Bulukumba',
  BULUNGANBULONGAN: 'Bulungan Bulongan',
  BUNGO: 'Bungo',
  BUOL: 'Buol',
  BURUSELATAN: 'South Buru',
  BUTON: 'Buton',
  BUTONUTARA: 'North Buton',
  CIAMIS: 'Ciamis',
  CIANJUR: 'Cianjur',
  CILACAP: 'Cilacap',
  CILEGON: 'Cilegon',
  CIMAHI: 'Cimahi',
  CIREBON: 'Cirebon',
  DAIRI: 'Dairi',
  DELISERDANG: 'Deli Serdang',
  DEMAK: 'Demak',
  DENPASAR: 'Denpasar',
  DEPOK: 'Depok',
  DHARMASRAYA: 'Dharmasraya',
  DOGIYAI: 'Dogiyai',
  DOMPU: 'Dompu',
  DONGGALA: 'Donggala',
  DUMAI: 'Dumai',
  EMPATLAWANG: 'Empat Lawang',
  ENDE: 'Ende',
  ENREKANG: 'Enrekang',
  FAKFAK: 'Fakfak',
  GARUT: 'Garut',
  GAYOLUES: 'Gayo Lues',
  GIANYAR: 'Gianyar',
  GORONTALO: 'Gorontalo',
  GORONTALOUTARA: 'North Gorontalo',
  GOWA: 'Gowa',
  GRESIK: 'Gresik',
  GROBOGAN: 'Grobogan',
  GUNUNGKIDUL: 'Gunung Kidul',
  GUNUNGMAS: 'Gunung Mas',
  GUNUNGSITOLI: 'Gunungsitoli',
  HULUSUNGAISELATAN: 'South Hulu Sungai',
  HULUSUNGAITENGAH: 'Central Hulu Sungai',
  HULUSUNGAIUTARA: 'North Hulu Sungai',
  HUMBANGHASUNDUTAN: 'Humbang Hasundutan',
  INDRAGIRIHILIR: 'Indragiri Hilir',
  INDRAGIRIHULU: 'Indragiri Hulu',
  INDRAMAYU: 'Indramayu',
  JAKARTABARAT: 'West Jakarta',
  JAKARTAPUSAT: 'Central Jakarta',
  JAKARTASELATAN: 'South Jakarta',
  JAKARTATIMUR: 'East Jakarta',
  JAKARTAUTARA: 'North Jakarta',
  JAMBI: 'Jambi',
  JAYAPURA: 'Jayapura',
  JAYAWIJAYA: 'Jayawijaya',
  JEMBER: 'Jember',
  JEMBRANA: 'Jembrana',
  JENEPONTO: 'Jeneponto',
  JEPARA: 'Jepara',
  JOMBANG: 'Jombang',
  KAMPAR: 'Kampar',
  KAPUAS: 'Kapuas',
  KAPUASHULU: 'Kapuas Hulu',
  KARANGANYAR: 'Karanganyar',
  KARANGASEM: 'Karangasem',
  KARAWANG: 'Karawang',
  KARIMUN: 'Karimun',
  KARO: 'Karo',
  KATINGAN: 'Katingan',
  KAUR: 'Kaur',
  KAYONGUTARA: 'North Kayong',
  KEBUMEN: 'Kebumen',
  KEDIRI: 'Kediri',
  KEEROM: 'Keerom',
  KENDAL: 'Kendal',
  KENDARI: 'Kendari',
  KEPAHIANG: 'Kepahiang',
  KEPULAUANANAMBAS: 'Kepulauan Anambas',
  KEPULAUANARU: 'Kepulauan Aru',
  KEPULAUANMENTAWAI: 'Kepulauan Mentawai',
  KEPULAUANMERANTI: 'Kepulauan Meranti',
  KEPULAUANSANGIHE: 'Kepulauan Sangihe',
  KEPULAUANSERIBU: 'Kepulauan Seribu',
  KEPULAUANSIAUTAGULANDANGBIAROSITARO:
    'Kepulauan Siau Tagulandang Biaro Sitaro',
  KEPULAUANTALAUD: 'Kepulauan Talaud',
  KEPULAUANYAPENYAPENWAROPEN: 'Kepulauan Yapen Yapen Waropen',
  KERINCI: 'Kerinci',
  KETAPANG: 'Ketapang',
  KLATEN: 'Klaten',
  KLUNGKUNG: 'Klungkung',
  KOLAKA: 'Kolaka',
  KOLAKAUTARA: 'North Kolaka',
  KONAWE: 'Konawe',
  KONAWESELATAN: 'South Konawe',
  KONAWEUTARA: 'North Konawe',
  KOTABARU: 'Kotabaru',
  KOTAMOBAGU: 'Kotamobagu',
  KOTAWARINGINBARAT: 'West Kotawaringin',
  KOTAWARINGINTIMUR: 'East Kotawaringin',
  KUANTANSINGINGI: 'Kuantan Singingi',
  KUBURAYA: 'Kubu Raya',
  KUDUS: 'Kudus',
  KULONPROGO: 'Kulon Progo',
  KUNINGAN: 'Kuningan',
  KUPANG: 'Kupang',
  KUTAIBARAT: 'West Kutai',
  KUTAIKARTANEGARA: 'Kutai Kartanegara',
  KUTAITIMUR: 'East Kutai',
  LABUHANBATU: 'Labuhan Batu',
  LABUHANBATUSELATAN: 'South Labuhan Batu',
  LABUHANBATUUTARA: 'North Labuhan Batu',
  LAHAT: 'Lahat',
  LAMANDAU: 'Lamandau',
  LAMONGAN: 'Lamongan',
  LAMPUNGBARAT: 'West Lampung',
  LAMPUNGSELATAN: 'South Lampung',
  LAMPUNGTENGAH: 'Central Lampung',
  LAMPUNGTIMUR: 'East Lampung',
  LAMPUNGUTARA: 'North Lampung',
  LANDAK: 'Landak',
  LANGKAT: 'Langkat',
  LANGSA: 'Langsa',
  LEBAK: 'Lebak',
  LEBONG: 'Lebong',
  LHOKSEUMAWE: 'Lhokseumawe',
  LIMAPULUHKOTOKOTA: 'Lima Puluh Koto/Kota',
  LINGGA: 'Lingga',
  LOMBOKBARAT: 'West Lombok',
  LOMBOKTENGAH: 'Central Lombok',
  LOMBOKTIMUR: 'East Lombok',
  LOMBOKUTARA: 'North Lombok',
  LUBUKLINGGAU: 'Lubuk Linggau',
  LUMAJANG: 'Lumajang',
  LUWU: 'Luwu',
  LUWUTIMUR: 'Luwu Timur',
  LUWUUTARA: 'North Luwu',
  MADIUN: 'Madiun',
  MAGELANG: 'Magelang',
  MAGETAN: 'Magetan',
  MAJALENGKA: 'Majalengka',
  MAJENE: 'Majene',
  MAKASSAR: 'Makassar',
  MALANG: 'Malang',
  MALINAU: 'Malinau',
  MALUKUTENGAH: 'Central Maluku',
  MALUKUTENGGARA: 'Southeast Maluku',
  MAMASA: 'Mamasa',
  MAMUJU: 'Mamuju',
  MAMUJUUTARA: 'North Mamuju',
  MANADO: 'Manado',
  MANDAILINGNATAL: 'Mandailing Natal',
  MANOKWARI: 'Manokwari',
  MAROS: 'Maros',
  MATARAM: 'Mataram',
  MEDAN: 'Medan',
  MELAWI: 'Melawi',
  MERANGIN: 'Merangin',
  MERAUKE: 'Merauke',
  MESUJI: 'Mesuji',
  METRO: 'Metro',
  MIMIKA: 'Mimika',
  MINAHASA: 'Minahasa',
  MINAHASASELATAN: 'South Minahasa',
  MINAHASATENGGARA: 'Southeast Minahasa',
  MINAHASAUTARA: 'North Minahasa',
  MOJOKERTO: 'Mojokerto',
  MOROWALI: 'Morowali',
  MUARAENIM: 'Muara Enim',
  MUAROJAMBI: 'Muaro Jambi',
  MUKOMUKO: 'Muko Muko',
  MUNA: 'Muna',
  MURUNGRAYA: 'Murung Raya',
  MUSIBANYUASIN: 'Musi Banyuasin',
  MUSIRAWAS: 'Musi Rawas',
  NABIRE: 'Nabire',
  NAGANRAYA: 'Nagan Raya',
  NDUGA: 'Nduga',
  NGANJUK: 'Nganjuk',
  NGAWI: 'Ngawi',
  NIAS: 'Nias',
  NIASBARAT: 'West Nias',
  NIASSELATAN: 'South Nias',
  NIASUTARA: 'North Nias',
  NUNUKAN: 'Nunukan',
  OGANILIR: 'Ogan Ilir',
  OGANKOMERINGILIR: 'Ogan Komering Ilir',
  OGANKOMERINGULU: 'Ogan Komering Ulu',
  OGANKOMERINGULUSELATAN: 'South Ogan Komering Ulu',
  OGANKOMERINGULUTIMUR: 'East Ogan Komering Ulu',
  OTHERS: 'Others',
  PACITAN: 'Pacitan',
  PADANG: 'Padang',
  PADANGLAWAS: 'Padang Lawas',
  PADANGLAWASUTARA: 'North Padang Lawas',
  PADANGPANJANG: 'Padang Panjang',
  PADANGPARIAMAN: 'Padang Pariaman',
  PADANGSIDEMPUAN: 'Padang Sidempuan',
  PAGARALAM: 'Pagar Alam',
  PAKPAKBHARAT: 'Pakpak Bharat',
  PALANGKARAYA: 'Palangka Raya',
  PALEMBANG: 'Palembang',
  PALOPO: 'Palopo',
  PALU: 'Palu',
  PAMEKASAN: 'Pamekasan',
  PANDEGLANG: 'Pandeglang',
  PANGANDARAN: 'Pangandaran',
  PANGKAJENEKEPULAUAN: 'Pangkajene Kepulauan',
  PANGKALPINANG: 'Pangkal Pinang',
  PAREPARE: 'Parepare',
  PARIAMAN: 'Pariaman',
  PARIGIMOUTONG: 'Parigi Moutong',
  PASAMAN: 'Pasaman',
  PASAMANBARAT: 'West Pasaman',
  PASER: 'Paser',
  PASURUAN: 'Pasuruan',
  PATI: 'Pati',
  PAYAKUMBUH: 'Payakumbuh',
  PEKALONGAN: 'Pekalongan',
  PEKANBARU: 'Pekanbaru',
  PELALAWAN: 'Pelalawan',
  PEMALANG: 'Pemalang',
  PEMATANGSIANTAR: 'Pematang Siantar',
  PENAJAMPASERUTARA: 'North Penajam Paser',
  PESAWARAN: 'Pesawaran',
  PESISIRBARAT: 'West Pesisir',
  PESISIRSELATAN: 'South Pesisir',
  PIDIE: 'Pidie',
  PIDIEJAYA: 'Pidie Jaya',
  PINRANG: 'Pinrang',
  POHUWATO: 'Pohuwato',
  POLEWALIMANDAR: 'Polewali Mandar',
  PONOROGO: 'Ponorogo',
  PONTIANAK: 'Pontianak',
  POSO: 'Poso',
  PRABUMULIH: 'Prabumulih',
  PRINGSEWU: 'Pringsewu',
  PROBOLINGGO: 'Probolinggo',
  PULANGPISAU: 'Pulang Pisau',
  PULAUMOROTAI: 'Pulau Morotai',
  PURBALINGGA: 'Purbalingga',
  PURWAKARTA: 'Purwakarta',
  PURWOREJO: 'Purworejo',
  REJANGLEBONG: 'Rejang Lebong',
  REMBANG: 'Rembang',
  ROKANHILIR: 'Rokan Hilir',
  ROKANHULU: 'Rokan Hulu',
  SABANG: 'Sabang',
  SALATIGA: 'Salatiga',
  SAMARINDA: 'Samarinda',
  SAMBAS: 'Sambas',
  SAMOSIR: 'Samosir',
  SAMPANG: 'Sampang',
  SANGGAU: 'Sanggau',
  SARMI: 'Sarmi',
  SAROLANGUN: 'Sarolangun',
  SAWAHLUNTO: 'Sawah Lunto',
  SEKADAU: 'Sekadau',
  SELAYARKEPULAUANSELAYAR: 'Selayar Kepulauan Selayar',
  SELUMA: 'Seluma',
  SEMARANG: 'Semarang',
  SERAMBAGIANBARAT: 'West Seram Bagian',
  SERANG: 'Serang',
  SERDANGBEDAGAI: 'Serdang Bedagai',
  SERUYAN: 'Seruyan',
  SIAK: 'Siak',
  SIBOLGA: 'Sibolga',
  SIDENRENGRAPPANGRAPANG: 'Sidenreng Rappang/Rapang',
  SIDOARJO: 'Sidoarjo',
  SIGI: 'Sigi',
  SIJUNJUNGSAWAHLUNTOSIJUNJUNG: 'Sijunjung Sawah Lunto Sijunjung',
  SIMALUNGUN: 'Simalungun',
  SIMEULUE: 'Simeulue',
  SINGKAWANG: 'Singkawang',
  SINJAI: 'Sinjai',
  SINTANG: 'Sintang',
  SITUBONDO: 'Situbondo',
  SLEMAN: 'Sleman',
  SOLOK: 'Solok',
  SOLOKSELATAN: 'South Solok',
  SOPPENG: 'Soppeng',
  SORONG: 'Sorong',
  SRAGEN: 'Sragen',
  SUBANG: 'Subang',
  SUBULUSSALAM: 'Subulussalam',
  SUKABUMI: 'Sukabumi',
  SUKAMARA: 'Sukamara',
  SUKOHARJO: 'Sukoharjo',
  SUMBABARATDAYA: 'Sumba Barat Daya',
  SUMBAWA: 'Sumbawa',
  SUMEDANG: 'Sumedang',
  SUMENEP: 'Sumenep',
  SUNGAIPENUH: 'Sungaipenuh',
  SURABAYA: 'Surabaya',
  SURAKARTASOLO: 'Surakarta Solo',
  TABALONG: 'Tabalong',
  TABANAN: 'Tabanan',
  TAKALAR: 'Takalar',
  TANAHBUMBU: 'Tanah Bumbu',
  TANAHDATAR: 'Tanah Datar',
  TANAHLAUT: 'Tanah Laut',
  TANATIDUNG: 'Tana Tidung',
  TANATORAJA: 'Tana Toraja',
  TANGERANG: 'Tangerang',
  TANGERANGSELATAN: 'South Tangerang',
  TANGGAMUS: 'Tanggamus',
  TANJUNGBALAI: 'Tanjung Balai',
  TANJUNGJABUNGBARAT: 'West Tanjung Jabung',
  TANJUNGJABUNGTIMUR: 'East Tanjung Jabung',
  TANJUNGPINANG: 'Tanjung Pinang',
  TAPANULISELATAN: 'South Tapanuli',
  TAPANULITENGAH: 'Central Tapanuli',
  TAPANULIUTARA: 'North Tapanuli',
  TAPIN: 'Tapin',
  TARAKAN: 'Tarakan',
  TASIKMALAYA: 'Tasikmalaya',
  TEBINGTINGGI: 'Tebing Tinggi',
  TEBO: 'Tebo',
  TEGAL: 'Tegal',
  TELUKBINTUNI: 'Teluk Bintuni',
  TEMANGGUNG: 'Temanggung',
  TERNATE: 'Ternate',
  TIMORTENGAHUTARA: 'North Timor Tengah',
  TOBASAMOSIR: 'Toba Samosir',
  TOJOUNAUNA: 'Tojo Una-Una',
  TOLITOLI: 'Toli-Toli',
  TOMOHON: 'Tomohon',
  TORAJAUTARA: 'Toraja Utara',
  TRENGGALEK: 'Trenggalek',
  TUBAN: 'Tuban',
  TULANGBAWANG: 'Tulang Bawang',
  TULANGBAWANGBARAT: 'West Tulang Bawang',
  TULUNGAGUNG: 'Tulungagung',
  WAJO: 'Wajo',
  WAKATOBI: 'Wakatobi',
  WAYKANAN: 'Way Kanan',
  WONOGIRI: 'Wonogiri',
  WONOSOBO: 'Wonosobo',
  YOGYAKARTA: 'Yogyakarta',
}
export const cityValueMap = {
  AcehBarat: 'Aceh Barat',
  AcehBaratDaya: 'Aceh Barat Daya',
  AcehBesar: 'Aceh Besar',
  AcehJaya: 'Aceh Jaya',
  AcehSelatan: 'Aceh Selatan',
  AcehSingkil: 'Aceh Singkil',
  AcehTamiang: 'Aceh Tamiang',
  AcehTengah: 'Aceh Tengah',
  AcehTenggara: 'Aceh Tenggara',
  AcehTimur: 'Aceh Timur',
  AcehUtara: 'Aceh Utara',
  Agam: 'Agam',
  Alor: 'Alor',
  Ambon: 'Ambon',
  Asahan: 'Asahan',
  Asmat: 'Asmat',
  Badung: 'Badung',
  Balangan: 'Balangan',
  Balikpapan: 'Balikpapan',
  BandaAceh: 'Banda Aceh',
  BandarLampung: 'Bandar Lampung',
  Bandung: 'Bandung',
  BandungBarat: 'Bandung Barat',
  Banggai: 'Banggai',
  BanggaiKepulauan: 'Banggai Kepulauan',
  Bangka: 'Bangka',
  BangkaBarat: 'Bangka Barat',
  BangkaSelatan: 'Bangka Selatan',
  BangkaTengah: 'Bangka Tengah',
  Bangkalan: 'Bangkalan',
  Bangli: 'Bangli',
  Banjar: 'Banjar',
  Banjarbaru: 'Banjarbaru',
  Banjarmasin: 'Banjarmasin',
  Banjarnegara: 'Banjarnegara',
  Bantaeng: 'Bantaeng',
  Bantul: 'Bantul',
  Banyuasin: 'Banyuasin',
  Banyumas: 'Banyumas',
  Banyuwangi: 'Banyuwangi',
  BaritoKuala: 'Barito Kuala',
  BaritoSelatan: 'Barito Selatan',
  BaritoTimur: 'Barito Timur',
  BaritoUtara: 'Barito Utara',
  Barru: 'Barru',
  Batam: 'Batam',
  Batang: 'Batang',
  BatangHari: 'Batang Hari',
  Batu: 'Batu',
  BatuBara: 'Batu Bara',
  Bau: 'Bau',
  Bekasi: 'Bekasi',
  Belitung: 'Belitung',
  BelitungTimur: 'Belitung Timur',
  Belu: 'Belu',
  BenerMeriah: 'Bener Meriah',
  Bengkalis: 'Bengkalis',
  Bengkayang: 'Bengkayang',
  Bengkulu: 'Bengkulu',
  BengkuluSelatan: 'Bengkulu Selatan',
  BengkuluTengah: 'Bengkulu Tengah',
  BengkuluUtara: 'Bengkulu Utara',
  Berau: 'Berau',
  BiakNumfor: 'Biak Numfor',
  Bima: 'Bima',
  Binjai: 'Binjai',
  Bintan: 'Bintan',
  Bireuen: 'Bireuen',
  Bitung: 'Bitung',
  Blitar: 'Blitar',
  Blora: 'Blora',
  Boalemo: 'Boalemo',
  Bogor: 'Bogor',
  Bojonegoro: 'Bojonegoro',
  'BolaangMongondow(Bolmong)': 'Bolaang Mongondow (Bolmong)',
  BolaangMongondowSelatan: 'Bolaang Mongondow Selatan',
  BolaangMongondowTimur: 'Bolaang Mongondow Timur',
  BolaangMongondowUtara: 'Bolaang Mongondow Utara',
  Bombana: 'Bombana',
  Bondowoso: 'Bondowoso',
  Bone: 'Bone',
  BoneBolango: 'Bone Bolango',
  Bontang: 'Bontang',
  BovenDigoel: 'Boven Digoel',
  Boyolali: 'Boyolali',
  Brebes: 'Brebes',
  Bukittinggi: 'Bukittinggi',
  Buleleng: 'Buleleng',
  Bulukumba: 'Bulukumba',
  'Bulungan(Bulongan)': 'Bulungan (Bulongan)',
  Bungo: 'Bungo',
  Buol: 'Buol',
  Buru: 'Buru',
  BuruSelatan: 'Buru Selatan',
  Buton: 'Buton',
  ButonUtara: 'Buton Utara',
  Ciamis: 'Ciamis',
  Cianjur: 'Cianjur',
  Cilacap: 'Cilacap',
  Cilegon: 'Cilegon',
  Cimahi: 'Cimahi',
  Cirebon: 'Cirebon',
  Dairi: 'Dairi',
  'Deiyai(Deliyai)': 'Deiyai (Deliyai)',
  DeliSerdang: 'Deli Serdang',
  Demak: 'Demak',
  Denpasar: 'Denpasar',
  Depok: 'Depok',
  Dharmasraya: 'Dharmasraya',
  Dogiyai: 'Dogiyai',
  Dompu: 'Dompu',
  Donggala: 'Donggala',
  Dumai: 'Dumai',
  EmpatLawang: 'Empat Lawang',
  Ende: 'Ende',
  Enrekang: 'Enrekang',
  Fakfak: 'Fakfak',
  FloresTimur: 'Flores Timur',
  Garut: 'Garut',
  GayoLues: 'Gayo Lues',
  Gianyar: 'Gianyar',
  Gorontalo: 'Gorontalo',
  GorontaloUtara: 'Gorontalo Utara',
  Gowa: 'Gowa',
  Gresik: 'Gresik',
  Grobogan: 'Grobogan',
  GunungKidul: 'Gunung Kidul',
  GunungMas: 'Gunung Mas',
  Gunungsitoli: 'Gunungsitoli',
  HalmaheraBarat: 'Halmahera Barat',
  HalmaheraSelatan: 'Halmahera Selatan',
  HalmaheraTengah: 'Halmahera Tengah',
  HalmaheraTimur: 'Halmahera Timur',
  HalmaheraUtara: 'Halmahera Utara',
  HuluSungaiSelatan: 'Hulu Sungai Selatan',
  HuluSungaiTengah: 'Hulu Sungai Tengah',
  HuluSungaiUtara: 'Hulu Sungai Utara',
  HumbangHasundutan: 'Humbang Hasundutan',
  IndragiriHilir: 'Indragiri Hilir',
  IndragiriHulu: 'Indragiri Hulu',
  Indramayu: 'Indramayu',
  IntanJaya: 'Intan Jaya',
  JakartaBarat: 'Jakarta Barat',
  JakartaPusat: 'Jakarta Pusat',
  JakartaSelatan: 'Jakarta Selatan',
  JakartaTimur: 'Jakarta Timur',
  JakartaUtara: 'Jakarta Utara',
  Jambi: 'Jambi',
  Jayapura: 'Jayapura',
  Jayawijaya: 'Jayawijaya',
  Jember: 'Jember',
  Jembrana: 'Jembrana',
  Jeneponto: 'Jeneponto',
  Jepara: 'Jepara',
  Jombang: 'Jombang',
  Kaimana: 'Kaimana',
  Kampar: 'Kampar',
  Kapuas: 'Kapuas',
  KapuasHulu: 'Kapuas Hulu',
  Karanganyar: 'Karanganyar',
  Karangasem: 'Karangasem',
  Karawang: 'Karawang',
  Karimun: 'Karimun',
  Karo: 'Karo',
  Katingan: 'Katingan',
  Kaur: 'Kaur',
  KayongUtara: 'Kayong Utara',
  Kebumen: 'Kebumen',
  Kediri: 'Kediri',
  Keerom: 'Keerom',
  Kendal: 'Kendal',
  Kendari: 'Kendari',
  Kepahiang: 'Kepahiang',
  KepulauanAnambas: 'Kepulauan Anambas',
  KepulauanAru: 'Kepulauan Aru',
  KepulauanMentawai: 'Kepulauan Mentawai',
  KepulauanMeranti: 'Kepulauan Meranti',
  KepulauanSangihe: 'Kepulauan Sangihe',
  KepulauanSeribu: 'Kepulauan Seribu',
  'KepulauanSiauTagulandangBiaro(Sitaro)':
    'Kepulauan Siau Tagulandang Biaro (Sitaro)',
  KepulauanSula: 'Kepulauan Sula',
  KepulauanTalaud: 'Kepulauan Talaud',
  'KepulauanYapen(YapenWaropen)': 'Kepulauan Yapen (Yapen Waropen)',
  Kerinci: 'Kerinci',
  Ketapang: 'Ketapang',
  Klaten: 'Klaten',
  Klungkung: 'Klungkung',
  Kolaka: 'Kolaka',
  KolakaUtara: 'Kolaka Utara',
  Konawe: 'Konawe',
  KonaweSelatan: 'Konawe Selatan',
  KonaweUtara: 'Konawe Utara',
  Kotabaru: 'Kotabaru',
  Kotamobagu: 'Kotamobagu',
  KotawaringinBarat: 'Kotawaringin Barat',
  KotawaringinTimur: 'Kotawaringin Timur',
  KuantanSingingi: 'Kuantan Singingi',
  KubuRaya: 'Kubu Raya',
  Kudus: 'Kudus',
  KulonProgo: 'Kulon Progo',
  Kuningan: 'Kuningan',
  Kupang: 'Kupang',
  KutaiBarat: 'Kutai Barat',
  KutaiKartanegara: 'Kutai Kartanegara',
  KutaiTimur: 'Kutai Timur',
  LabuhanBatu: 'Labuhan Batu',
  LabuhanBatuSelatan: 'Labuhan Batu Selatan',
  LabuhanBatuUtara: 'Labuhan Batu Utara',
  Lahat: 'Lahat',
  Lamandau: 'Lamandau',
  Lamongan: 'Lamongan',
  LampungBarat: 'Lampung Barat',
  LampungSelatan: 'Lampung Selatan',
  LampungTengah: 'Lampung Tengah',
  LampungTimur: 'Lampung Timur',
  LampungUtara: 'Lampung Utara',
  Landak: 'Landak',
  Langkat: 'Langkat',
  Langsa: 'Langsa',
  LannyJaya: 'Lanny Jaya',
  Lebak: 'Lebak',
  Lebong: 'Lebong',
  Lembata: 'Lembata',
  Lhokseumawe: 'Lhokseumawe',
  LimaPuluhKoto: 'Lima Puluh Koto',
  Lingga: 'Lingga',
  LombokBarat: 'Lombok Barat',
  LombokTengah: 'Lombok Tengah',
  LombokTimur: 'Lombok Timur',
  LombokUtara: 'Lombok Utara',
  LubukLinggau: 'Lubuk Linggau',
  Lumajang: 'Lumajang',
  Luwu: 'Luwu',
  LuwuTimur: 'Luwu Timur',
  LuwuUtara: 'Luwu Utara',
  Madiun: 'Madiun',
  Magelang: 'Magelang',
  Magetan: 'Magetan',
  Majalengka: 'Majalengka',
  Majene: 'Majene',
  Makassar: 'Makassar',
  Malang: 'Malang',
  Malinau: 'Malinau',
  MalukuBaratDaya: 'Maluku Barat Daya',
  MalukuTengah: 'Maluku Tengah',
  MalukuTenggara: 'Maluku Tenggara',
  MalukuTenggaraBarat: 'Maluku Tenggara Barat',
  Mamasa: 'Mamasa',
  MamberamoRaya: 'Mamberamo Raya',
  MamberamoTengah: 'Mamberamo Tengah',
  Mamuju: 'Mamuju',
  MamujuUtara: 'Mamuju Utara',
  Manado: 'Manado',
  MandailingNatal: 'Mandailing Natal',
  Manggarai: 'Manggarai',
  ManggaraiBarat: 'Manggarai Barat',
  ManggaraiTimur: 'Manggarai Timur',
  Manokwari: 'Manokwari',
  ManokwariSelatan: 'Manokwari Selatan',
  Mappi: 'Mappi',
  Maros: 'Maros',
  Mataram: 'Mataram',
  Maybrat: 'Maybrat',
  Medan: 'Medan',
  Melawi: 'Melawi',
  Merangin: 'Merangin',
  Merauke: 'Merauke',
  Mesuji: 'Mesuji',
  Metro: 'Metro',
  Mimika: 'Mimika',
  Minahasa: 'Minahasa',
  MinahasaSelatan: 'Minahasa Selatan',
  MinahasaTenggara: 'Minahasa Tenggara',
  MinahasaUtara: 'Minahasa Utara',
  Mojokerto: 'Mojokerto',
  Morowali: 'Morowali',
  MuaraEnim: 'Muara Enim',
  MuaroJambi: 'Muaro Jambi',
  MukoMuko: 'Muko Muko',
  Muna: 'Muna',
  MurungRaya: 'Murung Raya',
  MusiBanyuasin: 'Musi Banyuasin',
  MusiRawas: 'Musi Rawas',
  Nabire: 'Nabire',
  NaganRaya: 'Nagan Raya',
  Nagekeo: 'Nagekeo',
  Natuna: 'Natuna',
  Nduga: 'Nduga',
  Ngada: 'Ngada',
  Nganjuk: 'Nganjuk',
  Ngawi: 'Ngawi',
  Nias: 'Nias',
  NiasBarat: 'Nias Barat',
  NiasSelatan: 'Nias Selatan',
  NiasUtara: 'Nias Utara',
  Nunukan: 'Nunukan',
  OganIlir: 'Ogan Ilir',
  OganKomeringIlir: 'Ogan Komering Ilir',
  OganKomeringUlu: 'Ogan Komering Ulu',
  OganKomeringUluSelatan: 'Ogan Komering Ulu Selatan',
  OganKomeringUluTimur: 'Ogan Komering Ulu Timur',
  Pacitan: 'Pacitan',
  Padang: 'Padang',
  PadangLawas: 'Padang Lawas',
  PadangLawasUtara: 'Padang Lawas Utara',
  PadangPanjang: 'Padang Panjang',
  PadangPariaman: 'Padang Pariaman',
  PadangSidempuan: 'Padang Sidempuan',
  PagarAlam: 'Pagar Alam',
  PakpakBharat: 'Pakpak Bharat',
  PalangkaRaya: 'Palangka Raya',
  Palembang: 'Palembang',
  Palopo: 'Palopo',
  Palu: 'Palu',
  Pamekasan: 'Pamekasan',
  Pandeglang: 'Pandeglang',
  Pangandaran: 'Pangandaran',
  PangkajeneKepulauan: 'Pangkajene Kepulauan',
  PangkalPinang: 'Pangkal Pinang',
  Paniai: 'Paniai',
  Parepare: 'Parepare',
  Pariaman: 'Pariaman',
  ParigiMoutong: 'Parigi Moutong',
  Pasaman: 'Pasaman',
  PasamanBarat: 'Pasaman Barat',
  Paser: 'Paser',
  Pasuruan: 'Pasuruan',
  Pati: 'Pati',
  Payakumbuh: 'Payakumbuh',
  PegununganArfak: 'Pegunungan Arfak',
  PegununganBintang: 'Pegunungan Bintang',
  Pekalongan: 'Pekalongan',
  Pekanbaru: 'Pekanbaru',
  Pelalawan: 'Pelalawan',
  Pemalang: 'Pemalang',
  PematangSiantar: 'Pematang Siantar',
  PenajamPaserUtara: 'Penajam Paser Utara',
  Pesawaran: 'Pesawaran',
  PesisirBarat: 'Pesisir Barat',
  PesisirSelatan: 'Pesisir Selatan',
  Pidie: 'Pidie',
  PidieJaya: 'Pidie Jaya',
  Pinrang: 'Pinrang',
  Pohuwato: 'Pohuwato',
  PolewaliMandar: 'Polewali Mandar',
  Ponorogo: 'Ponorogo',
  Pontianak: 'Pontianak',
  Poso: 'Poso',
  Prabumulih: 'Prabumulih',
  Pringsewu: 'Pringsewu',
  Probolinggo: 'Probolinggo',
  PulangPisau: 'Pulang Pisau',
  PulauMorotai: 'Pulau Morotai',
  Puncak: 'Puncak',
  PuncakJaya: 'Puncak Jaya',
  Purbalingga: 'Purbalingga',
  Purwakarta: 'Purwakarta',
  Purworejo: 'Purworejo',
  RajaAmpat: 'Raja Ampat',
  RejangLebong: 'Rejang Lebong',
  Rembang: 'Rembang',
  RokanHilir: 'Rokan Hilir',
  RokanHulu: 'Rokan Hulu',
  RoteNdao: 'Rote Ndao',
  Sabang: 'Sabang',
  SabuRaijua: 'Sabu Raijua',
  Salatiga: 'Salatiga',
  Samarinda: 'Samarinda',
  Sambas: 'Sambas',
  Samosir: 'Samosir',
  Sampang: 'Sampang',
  Sanggau: 'Sanggau',
  Sarmi: 'Sarmi',
  Sarolangun: 'Sarolangun',
  SawahLunto: 'Sawah Lunto',
  Sekadau: 'Sekadau',
  'Selayar(KepulauanSelayar)': 'Selayar (Kepulauan Selayar)',
  Seluma: 'Seluma',
  Semarang: 'Semarang',
  SeramBagianBarat: 'Seram Bagian Barat',
  SeramBagianTimur: 'Seram Bagian Timur',
  Serang: 'Serang',
  SerdangBedagai: 'Serdang Bedagai',
  Seruyan: 'Seruyan',
  Siak: 'Siak',
  Sibolga: 'Sibolga',
  SidenrengRappang: 'Sidenreng Rappang',
  Sidoarjo: 'Sidoarjo',
  Sigi: 'Sigi',
  'Sijunjung(SawahLuntoSijunjung)': 'Sijunjung (Sawah Lunto Sijunjung)',
  Sikka: 'Sikka',
  Simalungun: 'Simalungun',
  Simeulue: 'Simeulue',
  Singkawang: 'Singkawang',
  Sinjai: 'Sinjai',
  Sintang: 'Sintang',
  Situbondo: 'Situbondo',
  Sleman: 'Sleman',
  Solok: 'Solok',
  SolokSelatan: 'Solok Selatan',
  Soppeng: 'Soppeng',
  Sorong: 'Sorong',
  SorongSelatan: 'Sorong Selatan',
  Sragen: 'Sragen',
  Subang: 'Subang',
  Subulussalam: 'Subulussalam',
  Sukabumi: 'Sukabumi',
  Sukamara: 'Sukamara',
  Sukoharjo: 'Sukoharjo',
  SumbaBarat: 'Sumba Barat',
  SumbaBaratDaya: 'Sumba Barat Daya',
  SumbaTengah: 'Sumba Tengah',
  SumbaTimur: 'Sumba Timur',
  Sumbawa: 'Sumbawa',
  SumbawaBarat: 'Sumbawa Barat',
  Sumedang: 'Sumedang',
  Sumenep: 'Sumenep',
  Sungaipenuh: 'Sungaipenuh',
  Supiori: 'Supiori',
  Surabaya: 'Surabaya',
  'Surakarta(Solo)': 'Surakarta (Solo)',
  Tabalong: 'Tabalong',
  Tabanan: 'Tabanan',
  Takalar: 'Takalar',
  Tambrauw: 'Tambrauw',
  TanaTidung: 'Tana Tidung',
  TanaToraja: 'Tana Toraja',
  TanahBumbu: 'Tanah Bumbu',
  TanahDatar: 'Tanah Datar',
  TanahLaut: 'Tanah Laut',
  Tangerang: 'Tangerang',
  TangerangSelatan: 'Tangerang Selatan',
  Tanggamus: 'Tanggamus',
  TanjungBalai: 'Tanjung Balai',
  TanjungJabungBarat: 'Tanjung Jabung Barat',
  TanjungJabungTimur: 'Tanjung Jabung Timur',
  TanjungPinang: 'Tanjung Pinang',
  TapanuliSelatan: 'Tapanuli Selatan',
  TapanuliTengah: 'Tapanuli Tengah',
  TapanuliUtara: 'Tapanuli Utara',
  Tapin: 'Tapin',
  Tarakan: 'Tarakan',
  Tasikmalaya: 'Tasikmalaya',
  TebingTinggi: 'Tebing Tinggi',
  Tebo: 'Tebo',
  Tegal: 'Tegal',
  TelukBintuni: 'Teluk Bintuni',
  TelukWondama: 'Teluk Wondama',
  Temanggung: 'Temanggung',
  Ternate: 'Ternate',
  TidoreKepulauan: 'Tidore Kepulauan',
  TimorTengahSelatan: 'Timor Tengah Selatan',
  TimorTengahUtara: 'Timor Tengah Utara',
  TobaSamosir: 'Toba Samosir',
  TojoUna: 'Tojo Una',
  Toli: 'Toli',
  Tolikara: 'Tolikara',
  Tomohon: 'Tomohon',
  TorajaUtara: 'Toraja Utara',
  Trenggalek: 'Trenggalek',
  Tual: 'Tual',
  Tuban: 'Tuban',
  TulangBawang: 'Tulang Bawang',
  TulangBawangBarat: 'Tulang Bawang Barat',
  Tulungagung: 'Tulungagung',
  Wajo: 'Wajo',
  Wakatobi: 'Wakatobi',
  Waropen: 'Waropen',
  WayKanan: 'Way Kanan',
  Wonogiri: 'Wonogiri',
  Wonosobo: 'Wonosobo',
  Yahukimo: 'Yahukimo',
  Yalimo: 'Yalimo',
  Yogyakarta: 'Yogyakarta',
}
